-- bang_gia_chuan_dam_okal (6 rows)
INSERT INTO bang_gia_chuan_dam_okal (stt, quy_cach, e2, veco_e1, veco_cp2, veco_f4s, hmr_e1) VALUES (1, '9mm', 180000, 195000, 214000, NULL, 252000);
INSERT INTO bang_gia_chuan_dam_okal (stt, quy_cach, e2, veco_e1, veco_cp2, veco_f4s, hmr_e1) VALUES (2, '12mm', 233000, 252000, 278000, NULL, 336000);
INSERT INTO bang_gia_chuan_dam_okal (stt, quy_cach, e2, veco_e1, veco_cp2, veco_f4s, hmr_e1) VALUES (3, '15mm', 278000, 297000, 330000, NULL, NULL);
INSERT INTO bang_gia_chuan_dam_okal (stt, quy_cach, e2, veco_e1, veco_cp2, veco_f4s, hmr_e1) VALUES (4, '17mm', 306000, NULL, NULL, NULL, NULL);
INSERT INTO bang_gia_chuan_dam_okal (stt, quy_cach, e2, veco_e1, veco_cp2, veco_f4s, hmr_e1) VALUES (5, '18mm', 322000, 351000, 383000, 600000, 450000);
INSERT INTO bang_gia_chuan_dam_okal (stt, quy_cach, e2, veco_e1, veco_cp2, veco_f4s, hmr_e1) VALUES (6, '25mm', 478000, 520000, 568000, NULL, NULL);
-- bang_gia_chuan_mdf_hdf (14 rows)
INSERT INTO bang_gia_chuan_mdf_hdf (stt, quy_cach, vn_ldf_e2, vn_mdf_e2, vn_mdf_cp2, vn_hdf_hmr_e2, vn_hdf_hmr_e1, th_mdf_e2, th_hdf_hmr_e2, vn_lmr_e2, vn_mmr_e2, vn_hmr_e2, vn_hmr_e1, vn_hmr_cp2, th_mmr_e2, th_hmr_v313_e1) VALUES (1, '2.5mm', 68000, 68000, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO bang_gia_chuan_mdf_hdf (stt, quy_cach, vn_ldf_e2, vn_mdf_e2, vn_mdf_cp2, vn_hdf_hmr_e2, vn_hdf_hmr_e1, th_mdf_e2, th_hdf_hmr_e2, vn_lmr_e2, vn_mmr_e2, vn_hmr_e2, vn_hmr_e1, vn_hmr_cp2, th_mmr_e2, th_hmr_v313_e1) VALUES (2, '3mm', 82000, 82000, NULL, NULL, NULL, NULL, NULL, 108000, 108000, NULL, NULL, NULL, NULL, NULL);
INSERT INTO bang_gia_chuan_mdf_hdf (stt, quy_cach, vn_ldf_e2, vn_mdf_e2, vn_mdf_cp2, vn_hdf_hmr_e2, vn_hdf_hmr_e1, th_mdf_e2, th_hdf_hmr_e2, vn_lmr_e2, vn_mmr_e2, vn_hmr_e2, vn_hmr_e1, vn_hmr_cp2, th_mmr_e2, th_hmr_v313_e1) VALUES (3, '4mm', 97000, 97000, NULL, NULL, NULL, 97000, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO bang_gia_chuan_mdf_hdf (stt, quy_cach, vn_ldf_e2, vn_mdf_e2, vn_mdf_cp2, vn_hdf_hmr_e2, vn_hdf_hmr_e1, th_mdf_e2, th_hdf_hmr_e2, vn_lmr_e2, vn_mmr_e2, vn_hmr_e2, vn_hmr_e1, vn_hmr_cp2, th_mmr_e2, th_hmr_v313_e1) VALUES (4, '4.75mm', 114000, 114000, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO bang_gia_chuan_mdf_hdf (stt, quy_cach, vn_ldf_e2, vn_mdf_e2, vn_mdf_cp2, vn_hdf_hmr_e2, vn_hdf_hmr_e1, th_mdf_e2, th_hdf_hmr_e2, vn_lmr_e2, vn_mmr_e2, vn_hmr_e2, vn_hmr_e1, vn_hmr_cp2, th_mmr_e2, th_hmr_v313_e1) VALUES (5, '5.5mm', 136000, 136000, NULL, NULL, NULL, NULL, NULL, 182000, 182000, NULL, NULL, NULL, NULL, NULL);
INSERT INTO bang_gia_chuan_mdf_hdf (stt, quy_cach, vn_ldf_e2, vn_mdf_e2, vn_mdf_cp2, vn_hdf_hmr_e2, vn_hdf_hmr_e1, th_mdf_e2, th_hdf_hmr_e2, vn_lmr_e2, vn_mmr_e2, vn_hmr_e2, vn_hmr_e1, vn_hmr_cp2, th_mmr_e2, th_hmr_v313_e1) VALUES (6, '6mm', NULL, NULL, 181000, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO bang_gia_chuan_mdf_hdf (stt, quy_cach, vn_ldf_e2, vn_mdf_e2, vn_mdf_cp2, vn_hdf_hmr_e2, vn_hdf_hmr_e1, th_mdf_e2, th_hdf_hmr_e2, vn_lmr_e2, vn_mmr_e2, vn_hmr_e2, vn_hmr_e1, vn_hmr_cp2, th_mmr_e2, th_hmr_v313_e1) VALUES (7, '8mm', 170000, 170000, NULL, 303000, 330000, 170000, NULL, 190000, 190000, NULL, NULL, 285000, NULL, NULL);
INSERT INTO bang_gia_chuan_mdf_hdf (stt, quy_cach, vn_ldf_e2, vn_mdf_e2, vn_mdf_cp2, vn_hdf_hmr_e2, vn_hdf_hmr_e1, th_mdf_e2, th_hdf_hmr_e2, vn_lmr_e2, vn_mmr_e2, vn_hmr_e2, vn_hmr_e1, vn_hmr_cp2, th_mmr_e2, th_hmr_v313_e1) VALUES (8, '9mm', 188000, 188000, 263000, NULL, NULL, 188000, NULL, 210000, 210000, NULL, 327000, 338000, 320000, NULL);
INSERT INTO bang_gia_chuan_mdf_hdf (stt, quy_cach, vn_ldf_e2, vn_mdf_e2, vn_mdf_cp2, vn_hdf_hmr_e2, vn_hdf_hmr_e1, th_mdf_e2, th_hdf_hmr_e2, vn_lmr_e2, vn_mmr_e2, vn_hmr_e2, vn_hmr_e1, vn_hmr_cp2, th_mmr_e2, th_hmr_v313_e1) VALUES (9, '12mm', 244000, 244000, 333000, NULL, 537000, 244000, NULL, 278000, 278000, NULL, NULL, NULL, NULL, NULL);
INSERT INTO bang_gia_chuan_mdf_hdf (stt, quy_cach, vn_ldf_e2, vn_mdf_e2, vn_mdf_cp2, vn_hdf_hmr_e2, vn_hdf_hmr_e1, th_mdf_e2, th_hdf_hmr_e2, vn_lmr_e2, vn_mmr_e2, vn_hmr_e2, vn_hmr_e1, vn_hmr_cp2, th_mmr_e2, th_hmr_v313_e1) VALUES (10, '15mm', 300000, 300000, 414000, NULL, NULL, NULL, 334000, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO bang_gia_chuan_mdf_hdf (stt, quy_cach, vn_ldf_e2, vn_mdf_e2, vn_mdf_cp2, vn_hdf_hmr_e2, vn_hdf_hmr_e1, th_mdf_e2, th_hdf_hmr_e2, vn_lmr_e2, vn_mmr_e2, vn_hmr_e2, vn_hmr_e1, vn_hmr_cp2, th_mmr_e2, th_hmr_v313_e1) VALUES (11, '17mm', 328000, 328000, 461000, NULL, 601000, NULL, 672000, 358000, 358000, 478000, 560000, 583000, 527000, 683000);
INSERT INTO bang_gia_chuan_mdf_hdf (stt, quy_cach, vn_ldf_e2, vn_mdf_e2, vn_mdf_cp2, vn_hdf_hmr_e2, vn_hdf_hmr_e1, th_mdf_e2, th_hdf_hmr_e2, vn_lmr_e2, vn_mmr_e2, vn_hmr_e2, vn_hmr_e1, vn_hmr_cp2, th_mmr_e2, th_hmr_v313_e1) VALUES (12, '18mm', 352000, 352000, 490000, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO bang_gia_chuan_mdf_hdf (stt, quy_cach, vn_ldf_e2, vn_mdf_e2, vn_mdf_cp2, vn_hdf_hmr_e2, vn_hdf_hmr_e1, th_mdf_e2, th_hdf_hmr_e2, vn_lmr_e2, vn_mmr_e2, vn_hmr_e2, vn_hmr_e1, vn_hmr_cp2, th_mmr_e2, th_hmr_v313_e1) VALUES (13, '21mm', 521000, 521000, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO bang_gia_chuan_mdf_hdf (stt, quy_cach, vn_ldf_e2, vn_mdf_e2, vn_mdf_cp2, vn_hdf_hmr_e2, vn_hdf_hmr_e1, th_mdf_e2, th_hdf_hmr_e2, vn_lmr_e2, vn_mmr_e2, vn_hmr_e2, vn_hmr_e1, vn_hmr_cp2, th_mmr_e2, th_hmr_v313_e1) VALUES (14, '25mm', 555000, 607000, 741000, NULL, NULL, 620000, NULL, 680000, 770000, NULL, NULL, 823000, NULL, NULL);
-- bang_gia_chuan_phu_thu_melamine (3 rows)
INSERT INTO bang_gia_chuan_phu_thu_melamine (stt, mo_ta, basic_1m, basic_2m, eco_1m, eco_2m, standard_1m, standard_2m, premium_wood_art_1m, premium_wood_art_2m, premium_color_1m, premium_color_2m, superb_1m, superb_2m) VALUES (1, 'Đơn giá', 80000, 120000, 90000, 130000, 90000, 130000, 90000, 130000, 100000, 150000, 110000, 190000);
INSERT INTO bang_gia_chuan_phu_thu_melamine (stt, mo_ta, basic_1m, basic_2m, eco_1m, eco_2m, standard_1m, standard_2m, premium_wood_art_1m, premium_wood_art_2m, premium_color_1m, premium_color_2m, superb_1m, superb_2m) VALUES (2, 'Màu đặc biệt', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Màu 104', 'Màu 106');
INSERT INTO bang_gia_chuan_phu_thu_melamine (stt, mo_ta, basic_1m, basic_2m, eco_1m, eco_2m, standard_1m, standard_2m, premium_wood_art_1m, premium_wood_art_2m, premium_color_1m, premium_color_2m, superb_1m, superb_2m) VALUES (3, 'Đơn giá màu đặc biệt', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 160000, 230000);
-- bang_gia_chuan_mau_melamine (220 rows)
INSERT INTO bang_gia_chuan_mau_melamine (stt, nguon, nhom, loai, ma_mau, vi_tri) VALUES (1, '220', 'Basic', 'Color', '108', 1);
INSERT INTO bang_gia_chuan_mau_melamine (stt, nguon, nhom, loai, ma_mau, vi_tri) VALUES (1, '220', 'Economy', 'Wood', '029', 2);
INSERT INTO bang_gia_chuan_mau_melamine (stt, nguon, nhom, loai, ma_mau, vi_tri) VALUES (1, '220', 'Economy', 'Wood', '303', 3);
INSERT INTO bang_gia_chuan_mau_melamine (stt, nguon, nhom, loai, ma_mau, vi_tri) VALUES (1, '220', 'Economy', 'Wood', '385', 4);
INSERT INTO bang_gia_chuan_mau_melamine (stt, nguon, nhom, loai, ma_mau, vi_tri) VALUES (1, '220', 'Economy', 'Wood', '402', 5);
INSERT INTO bang_gia_chuan_mau_melamine (stt, nguon, nhom, loai, ma_mau, vi_tri) VALUES (1, '220', 'Economy', 'Wood', '425', 6);
INSERT INTO bang_gia_chuan_mau_melamine (stt, nguon, nhom, loai, ma_mau, vi_tri) VALUES (1, '220', 'Economy', 'Wood', '444', 7);
INSERT INTO bang_gia_chuan_mau_melamine (stt, nguon, nhom, loai, ma_mau, vi_tri) VALUES (1, '220', 'Economy', 'Wood', '501', 8);
INSERT INTO bang_gia_chuan_mau_melamine (stt, nguon, nhom, loai, ma_mau, vi_tri) VALUES (1, '220', 'Economy', 'Wood', '601', 9);
INSERT INTO bang_gia_chuan_mau_melamine (stt, nguon, nhom, loai, ma_mau, vi_tri) VALUES (1, '220', 'Economy', 'Wood', '725', 10);
INSERT INTO bang_gia_chuan_mau_melamine (stt, nguon, nhom, loai, ma_mau, vi_tri) VALUES (1, '220', 'Economy', 'Art', 'Đ5', 11);
INSERT INTO bang_gia_chuan_mau_melamine (stt, nguon, nhom, loai, ma_mau, vi_tri) VALUES (1, '220', 'Economy', 'Color', '203', 12);
INSERT INTO bang_gia_chuan_mau_melamine (stt, nguon, nhom, loai, ma_mau, vi_tri) VALUES (1, '220', 'Standard', 'Wood', '0330', 13);
INSERT INTO bang_gia_chuan_mau_melamine (stt, nguon, nhom, loai, ma_mau, vi_tri) VALUES (1, '220', 'Standard', 'Wood', '4028', 14);
INSERT INTO bang_gia_chuan_mau_melamine (stt, nguon, nhom, loai, ma_mau, vi_tri) VALUES (1, '220', 'Standard', 'Art', '735', 15);
INSERT INTO bang_gia_chuan_mau_melamine (stt, nguon, nhom, loai, ma_mau, vi_tri) VALUES (1, '220', 'Standard', 'Color', 'Đ2', 16);
INSERT INTO bang_gia_chuan_mau_melamine (stt, nguon, nhom, loai, ma_mau, vi_tri) VALUES (1, '220', 'Premium', 'Art', '100', 17);
INSERT INTO bang_gia_chuan_mau_melamine (stt, nguon, nhom, loai, ma_mau, vi_tri) VALUES (1, '220', 'Premium', 'Color', '132', 18);
INSERT INTO bang_gia_chuan_mau_melamine (stt, nguon, nhom, loai, ma_mau, vi_tri) VALUES (1, '220', 'Premium', 'Wood', '301', 19);
INSERT INTO bang_gia_chuan_mau_melamine (stt, nguon, nhom, loai, ma_mau, vi_tri) VALUES (1, '220', 'Premium', 'Wood', '439', 20);
INSERT INTO bang_gia_chuan_mau_melamine (stt, nguon, nhom, loai, ma_mau, vi_tri) VALUES (1, '220', 'Premium', 'Wood', '708', 21);
INSERT INTO bang_gia_chuan_mau_melamine (stt, nguon, nhom, loai, ma_mau, vi_tri) VALUES (1, '220', 'Premium', 'Art', '571', 22);
INSERT INTO bang_gia_chuan_mau_melamine (stt, nguon, nhom, loai, ma_mau, vi_tri) VALUES (1, '220', 'Premium', 'Color', 'Đ6', 23);
INSERT INTO bang_gia_chuan_mau_melamine (stt, nguon, nhom, loai, ma_mau, vi_tri) VALUES (1, '220', 'Superb', 'Color', '021', 24);
INSERT INTO bang_gia_chuan_mau_melamine (stt, nguon, nhom, loai, ma_mau, vi_tri) VALUES (1, '220', 'Superb', 'Color', '200', 25);
INSERT INTO bang_gia_chuan_mau_melamine (stt, nguon, nhom, loai, ma_mau, vi_tri) VALUES (1, '220', 'Superb', 'Color', '033', 26);
INSERT INTO bang_gia_chuan_mau_melamine (stt, nguon, nhom, loai, ma_mau, vi_tri) VALUES (1, '220', 'Superb', 'Color', '104 (150Gr)', 27);
INSERT INTO bang_gia_chuan_mau_melamine (stt, nguon, nhom, loai, ma_mau, vi_tri) VALUES (2, '220', 'Basic', 'Color', '388-2', 1);
INSERT INTO bang_gia_chuan_mau_melamine (stt, nguon, nhom, loai, ma_mau, vi_tri) VALUES (2, '220', 'Economy', 'Wood', '0439', 2);
INSERT INTO bang_gia_chuan_mau_melamine (stt, nguon, nhom, loai, ma_mau, vi_tri) VALUES (2, '220', 'Economy', 'Wood', '320', 3);
INSERT INTO bang_gia_chuan_mau_melamine (stt, nguon, nhom, loai, ma_mau, vi_tri) VALUES (2, '220', 'Economy', 'Wood', '386', 4);
INSERT INTO bang_gia_chuan_mau_melamine (stt, nguon, nhom, loai, ma_mau, vi_tri) VALUES (2, '220', 'Economy', 'Wood', '403', 5);
INSERT INTO bang_gia_chuan_mau_melamine (stt, nguon, nhom, loai, ma_mau, vi_tri) VALUES (2, '220', 'Economy', 'Wood', '426', 6);
INSERT INTO bang_gia_chuan_mau_melamine (stt, nguon, nhom, loai, ma_mau, vi_tri) VALUES (2, '220', 'Economy', 'Wood', '445', 7);
INSERT INTO bang_gia_chuan_mau_melamine (stt, nguon, nhom, loai, ma_mau, vi_tri) VALUES (2, '220', 'Economy', 'Wood', '502', 8);
INSERT INTO bang_gia_chuan_mau_melamine (stt, nguon, nhom, loai, ma_mau, vi_tri) VALUES (2, '220', 'Economy', 'Wood', '609', 9);
INSERT INTO bang_gia_chuan_mau_melamine (stt, nguon, nhom, loai, ma_mau, vi_tri) VALUES (2, '220', 'Economy', 'Wood', '737', 10);
INSERT INTO bang_gia_chuan_mau_melamine (stt, nguon, nhom, loai, ma_mau, vi_tri) VALUES (2, '220', 'Economy', 'Art', 'Đ8', 11);
INSERT INTO bang_gia_chuan_mau_melamine (stt, nguon, nhom, loai, ma_mau, vi_tri) VALUES (2, '220', 'Standard', 'Wood', '23015', 12);
INSERT INTO bang_gia_chuan_mau_melamine (stt, nguon, nhom, loai, ma_mau, vi_tri) VALUES (2, '220', 'Standard', 'Wood', '4029', 13);
INSERT INTO bang_gia_chuan_mau_melamine (stt, nguon, nhom, loai, ma_mau, vi_tri) VALUES (2, '220', 'Standard', 'Art', '736', 14);
INSERT INTO bang_gia_chuan_mau_melamine (stt, nguon, nhom, loai, ma_mau, vi_tri) VALUES (2, '220', 'Standard', 'Color', 'Đ3', 15);
INSERT INTO bang_gia_chuan_mau_melamine (stt, nguon, nhom, loai, ma_mau, vi_tri) VALUES (2, '220', 'Premium', 'Color', '136', 16);
INSERT INTO bang_gia_chuan_mau_melamine (stt, nguon, nhom, loai, ma_mau, vi_tri) VALUES (2, '220', 'Premium', 'Wood', '302', 17);
INSERT INTO bang_gia_chuan_mau_melamine (stt, nguon, nhom, loai, ma_mau, vi_tri) VALUES (2, '220', 'Premium', 'Wood', '551', 18);
INSERT INTO bang_gia_chuan_mau_melamine (stt, nguon, nhom, loai, ma_mau, vi_tri) VALUES (2, '220', 'Premium', 'Wood', '714', 19);
INSERT INTO bang_gia_chuan_mau_melamine (stt, nguon, nhom, loai, ma_mau, vi_tri) VALUES (2, '220', 'Premium', 'Art', '572', 20);
INSERT INTO bang_gia_chuan_mau_melamine (stt, nguon, nhom, loai, ma_mau, vi_tri) VALUES (2, '220', 'Premium', 'Color', 'Đ7', 21);
INSERT INTO bang_gia_chuan_mau_melamine (stt, nguon, nhom, loai, ma_mau, vi_tri) VALUES (2, '220', 'Superb', 'Color', '041', 22);
INSERT INTO bang_gia_chuan_mau_melamine (stt, nguon, nhom, loai, ma_mau, vi_tri) VALUES (2, '220', 'Superb', 'Color', '025', 23);
INSERT INTO bang_gia_chuan_mau_melamine (stt, nguon, nhom, loai, ma_mau, vi_tri) VALUES (2, '220', 'Superb', 'Color', '034', 24);
INSERT INTO bang_gia_chuan_mau_melamine (stt, nguon, nhom, loai, ma_mau, vi_tri) VALUES (2, '220', 'Superb', 'Color', '106 (270Gr)', 25);
INSERT INTO bang_gia_chuan_mau_melamine (stt, nguon, nhom, loai, ma_mau, vi_tri) VALUES (3, '220', 'Basic', 'Color', '109', 1);
INSERT INTO bang_gia_chuan_mau_melamine (stt, nguon, nhom, loai, ma_mau, vi_tri) VALUES (3, '220', 'Economy', 'Wood', '161', 2);
INSERT INTO bang_gia_chuan_mau_melamine (stt, nguon, nhom, loai, ma_mau, vi_tri) VALUES (3, '220', 'Economy', 'Wood', '325', 3);
INSERT INTO bang_gia_chuan_mau_melamine (stt, nguon, nhom, loai, ma_mau, vi_tri) VALUES (3, '220', 'Economy', 'Wood', '388', 4);
INSERT INTO bang_gia_chuan_mau_melamine (stt, nguon, nhom, loai, ma_mau, vi_tri) VALUES (3, '220', 'Economy', 'Wood', '404', 5);
INSERT INTO bang_gia_chuan_mau_melamine (stt, nguon, nhom, loai, ma_mau, vi_tri) VALUES (3, '220', 'Economy', 'Wood', '427', 6);
INSERT INTO bang_gia_chuan_mau_melamine (stt, nguon, nhom, loai, ma_mau, vi_tri) VALUES (3, '220', 'Economy', 'Wood', '447', 7);
INSERT INTO bang_gia_chuan_mau_melamine (stt, nguon, nhom, loai, ma_mau, vi_tri) VALUES (3, '220', 'Economy', 'Wood', '503', 8);
INSERT INTO bang_gia_chuan_mau_melamine (stt, nguon, nhom, loai, ma_mau, vi_tri) VALUES (3, '220', 'Economy', 'Wood', '611', 9);
INSERT INTO bang_gia_chuan_mau_melamine (stt, nguon, nhom, loai, ma_mau, vi_tri) VALUES (3, '220', 'Economy', 'Wood', '740', 10);
INSERT INTO bang_gia_chuan_mau_melamine (stt, nguon, nhom, loai, ma_mau, vi_tri) VALUES (3, '220', 'Economy', 'Art', '901', 11);
INSERT INTO bang_gia_chuan_mau_melamine (stt, nguon, nhom, loai, ma_mau, vi_tri) VALUES (3, '220', 'Standard', 'Wood', '329', 12);
INSERT INTO bang_gia_chuan_mau_melamine (stt, nguon, nhom, loai, ma_mau, vi_tri) VALUES (3, '220', 'Standard', 'Wood', '4030', 13);
INSERT INTO bang_gia_chuan_mau_melamine (stt, nguon, nhom, loai, ma_mau, vi_tri) VALUES (3, '220', 'Standard', 'Art', '757', 14);
INSERT INTO bang_gia_chuan_mau_melamine (stt, nguon, nhom, loai, ma_mau, vi_tri) VALUES (3, '220', 'Standard', 'Color', 'Đ4', 15);
INSERT INTO bang_gia_chuan_mau_melamine (stt, nguon, nhom, loai, ma_mau, vi_tri) VALUES (3, '220', 'Premium', 'Color', '139', 16);
INSERT INTO bang_gia_chuan_mau_melamine (stt, nguon, nhom, loai, ma_mau, vi_tri) VALUES (3, '220', 'Premium', 'Wood', '311', 17);
INSERT INTO bang_gia_chuan_mau_melamine (stt, nguon, nhom, loai, ma_mau, vi_tri) VALUES (3, '220', 'Premium', 'Wood', '556', 18);
INSERT INTO bang_gia_chuan_mau_melamine (stt, nguon, nhom, loai, ma_mau, vi_tri) VALUES (3, '220', 'Premium', 'Wood', '719', 19);
INSERT INTO bang_gia_chuan_mau_melamine (stt, nguon, nhom, loai, ma_mau, vi_tri) VALUES (3, '220', 'Premium', 'Art', '524', 20);
INSERT INTO bang_gia_chuan_mau_melamine (stt, nguon, nhom, loai, ma_mau, vi_tri) VALUES (3, '220', 'Premium', 'Color', 'Đ9', 21);
INSERT INTO bang_gia_chuan_mau_melamine (stt, nguon, nhom, loai, ma_mau, vi_tri) VALUES (3, '220', 'Superb', 'Color', '030', 22);
INSERT INTO bang_gia_chuan_mau_melamine (stt, nguon, nhom, loai, ma_mau, vi_tri) VALUES (3, '220', 'Superb', 'Color', '0212', 23);
INSERT INTO bang_gia_chuan_mau_melamine (stt, nguon, nhom, loai, ma_mau, vi_tri) VALUES (3, '220', 'Superb', 'Color', '01 (105Gr)', 24);
INSERT INTO bang_gia_chuan_mau_melamine (stt, nguon, nhom, loai, ma_mau, vi_tri) VALUES (4, '220', 'Economy', 'Wood', '184', 1);
INSERT INTO bang_gia_chuan_mau_melamine (stt, nguon, nhom, loai, ma_mau, vi_tri) VALUES (4, '220', 'Economy', 'Wood', '330', 2);
INSERT INTO bang_gia_chuan_mau_melamine (stt, nguon, nhom, loai, ma_mau, vi_tri) VALUES (4, '220', 'Economy', 'Wood', '389', 3);
INSERT INTO bang_gia_chuan_mau_melamine (stt, nguon, nhom, loai, ma_mau, vi_tri) VALUES (4, '220', 'Economy', 'Wood', '405', 4);
INSERT INTO bang_gia_chuan_mau_melamine (stt, nguon, nhom, loai, ma_mau, vi_tri) VALUES (4, '220', 'Economy', 'Wood', '428', 5);
INSERT INTO bang_gia_chuan_mau_melamine (stt, nguon, nhom, loai, ma_mau, vi_tri) VALUES (4, '220', 'Economy', 'Wood', '448', 6);
INSERT INTO bang_gia_chuan_mau_melamine (stt, nguon, nhom, loai, ma_mau, vi_tri) VALUES (4, '220', 'Economy', 'Wood', '530', 7);
INSERT INTO bang_gia_chuan_mau_melamine (stt, nguon, nhom, loai, ma_mau, vi_tri) VALUES (4, '220', 'Economy', 'Wood', '612', 8);
INSERT INTO bang_gia_chuan_mau_melamine (stt, nguon, nhom, loai, ma_mau, vi_tri) VALUES (4, '220', 'Economy', 'Wood', '741', 9);
INSERT INTO bang_gia_chuan_mau_melamine (stt, nguon, nhom, loai, ma_mau, vi_tri) VALUES (4, '220', 'Economy', 'Art', '430', 10);
INSERT INTO bang_gia_chuan_mau_melamine (stt, nguon, nhom, loai, ma_mau, vi_tri) VALUES (4, '220', 'Standard', 'Wood', '336', 11);
INSERT INTO bang_gia_chuan_mau_melamine (stt, nguon, nhom, loai, ma_mau, vi_tri) VALUES (4, '220', 'Standard', 'Wood', '4457', 12);
INSERT INTO bang_gia_chuan_mau_melamine (stt, nguon, nhom, loai, ma_mau, vi_tri) VALUES (4, '220', 'Standard', 'Art', '759', 13);
INSERT INTO bang_gia_chuan_mau_melamine (stt, nguon, nhom, loai, ma_mau, vi_tri) VALUES (4, '220', 'Premium', 'Color', '142', 14);
INSERT INTO bang_gia_chuan_mau_melamine (stt, nguon, nhom, loai, ma_mau, vi_tri) VALUES (4, '220', 'Premium', 'Wood', '312', 15);
INSERT INTO bang_gia_chuan_mau_melamine (stt, nguon, nhom, loai, ma_mau, vi_tri) VALUES (4, '220', 'Premium', 'Wood', '590', 16);
INSERT INTO bang_gia_chuan_mau_melamine (stt, nguon, nhom, loai, ma_mau, vi_tri) VALUES (4, '220', 'Premium', 'Wood', '722', 17);
INSERT INTO bang_gia_chuan_mau_melamine (stt, nguon, nhom, loai, ma_mau, vi_tri) VALUES (4, '220', 'Premium', 'Art', '541', 18);
INSERT INTO bang_gia_chuan_mau_melamine (stt, nguon, nhom, loai, ma_mau, vi_tri) VALUES (4, '220', 'Premium', 'Color', 'Đ10', 19);
INSERT INTO bang_gia_chuan_mau_melamine (stt, nguon, nhom, loai, ma_mau, vi_tri) VALUES (4, '220', 'Superb', 'Color', '220', 20);
INSERT INTO bang_gia_chuan_mau_melamine (stt, nguon, nhom, loai, ma_mau, vi_tri) VALUES (4, '220', 'Superb', 'Color', '213', 21);
INSERT INTO bang_gia_chuan_mau_melamine (stt, nguon, nhom, loai, ma_mau, vi_tri) VALUES (4, '220', 'Superb', 'Color', '230', 22);
INSERT INTO bang_gia_chuan_mau_melamine (stt, nguon, nhom, loai, ma_mau, vi_tri) VALUES (5, '220', 'Economy', 'Wood', '331', 1);
INSERT INTO bang_gia_chuan_mau_melamine (stt, nguon, nhom, loai, ma_mau, vi_tri) VALUES (5, '220', 'Economy', 'Wood', '407', 2);
INSERT INTO bang_gia_chuan_mau_melamine (stt, nguon, nhom, loai, ma_mau, vi_tri) VALUES (5, '220', 'Economy', 'Wood', '429', 3);
INSERT INTO bang_gia_chuan_mau_melamine (stt, nguon, nhom, loai, ma_mau, vi_tri) VALUES (5, '220', 'Economy', 'Wood', '460', 4);
INSERT INTO bang_gia_chuan_mau_melamine (stt, nguon, nhom, loai, ma_mau, vi_tri) VALUES (5, '220', 'Economy', 'Wood', '577', 5);
INSERT INTO bang_gia_chuan_mau_melamine (stt, nguon, nhom, loai, ma_mau, vi_tri) VALUES (5, '220', 'Economy', 'Wood', '613', 6);
INSERT INTO bang_gia_chuan_mau_melamine (stt, nguon, nhom, loai, ma_mau, vi_tri) VALUES (5, '220', 'Economy', 'Wood', '750', 7);
INSERT INTO bang_gia_chuan_mau_melamine (stt, nguon, nhom, loai, ma_mau, vi_tri) VALUES (5, '220', 'Economy', 'Art', '431', 8);
INSERT INTO bang_gia_chuan_mau_melamine (stt, nguon, nhom, loai, ma_mau, vi_tri) VALUES (5, '220', 'Standard', 'Wood', '380', 9);
INSERT INTO bang_gia_chuan_mau_melamine (stt, nguon, nhom, loai, ma_mau, vi_tri) VALUES (5, '220', 'Standard', 'Wood', '504', 10);
INSERT INTO bang_gia_chuan_mau_melamine (stt, nguon, nhom, loai, ma_mau, vi_tri) VALUES (5, '220', 'Standard', 'Art', '776', 11);
INSERT INTO bang_gia_chuan_mau_melamine (stt, nguon, nhom, loai, ma_mau, vi_tri) VALUES (5, '220', 'Standard', 'Color', '0446', 12);
INSERT INTO bang_gia_chuan_mau_melamine (stt, nguon, nhom, loai, ma_mau, vi_tri) VALUES (5, '220', 'Premium', 'Color', '145', 13);
INSERT INTO bang_gia_chuan_mau_melamine (stt, nguon, nhom, loai, ma_mau, vi_tri) VALUES (5, '220', 'Premium', 'Wood', '321', 14);
INSERT INTO bang_gia_chuan_mau_melamine (stt, nguon, nhom, loai, ma_mau, vi_tri) VALUES (5, '220', 'Premium', 'Wood', '621', 15);
INSERT INTO bang_gia_chuan_mau_melamine (stt, nguon, nhom, loai, ma_mau, vi_tri) VALUES (5, '220', 'Premium', 'Wood', '787', 16);
INSERT INTO bang_gia_chuan_mau_melamine (stt, nguon, nhom, loai, ma_mau, vi_tri) VALUES (5, '220', 'Premium', 'Art', '545', 17);
INSERT INTO bang_gia_chuan_mau_melamine (stt, nguon, nhom, loai, ma_mau, vi_tri) VALUES (5, '220', 'Premium', 'Color', 'Đ11', 18);
INSERT INTO bang_gia_chuan_mau_melamine (stt, nguon, nhom, loai, ma_mau, vi_tri) VALUES (5, '220', 'Superb', 'Color', '073', 19);
INSERT INTO bang_gia_chuan_mau_melamine (stt, nguon, nhom, loai, ma_mau, vi_tri) VALUES (5, '220', 'Superb', 'Color', '215', 20);
INSERT INTO bang_gia_chuan_mau_melamine (stt, nguon, nhom, loai, ma_mau, vi_tri) VALUES (5, '220', 'Superb', 'Color', '204', 21);
INSERT INTO bang_gia_chuan_mau_melamine (stt, nguon, nhom, loai, ma_mau, vi_tri) VALUES (6, '220', 'Economy', 'Wood', '201', 1);
INSERT INTO bang_gia_chuan_mau_melamine (stt, nguon, nhom, loai, ma_mau, vi_tri) VALUES (6, '220', 'Economy', 'Wood', '332', 2);
INSERT INTO bang_gia_chuan_mau_melamine (stt, nguon, nhom, loai, ma_mau, vi_tri) VALUES (6, '220', 'Economy', 'Wood', '412', 3);
INSERT INTO bang_gia_chuan_mau_melamine (stt, nguon, nhom, loai, ma_mau, vi_tri) VALUES (6, '220', 'Economy', 'Wood', '432', 4);
INSERT INTO bang_gia_chuan_mau_melamine (stt, nguon, nhom, loai, ma_mau, vi_tri) VALUES (6, '220', 'Economy', 'Wood', '467', 5);
INSERT INTO bang_gia_chuan_mau_melamine (stt, nguon, nhom, loai, ma_mau, vi_tri) VALUES (6, '220', 'Economy', 'Wood', '614', 6);
INSERT INTO bang_gia_chuan_mau_melamine (stt, nguon, nhom, loai, ma_mau, vi_tri) VALUES (6, '220', 'Economy', 'Wood', '771', 7);
INSERT INTO bang_gia_chuan_mau_melamine (stt, nguon, nhom, loai, ma_mau, vi_tri) VALUES (6, '220', 'Standard', 'Wood', '410', 8);
INSERT INTO bang_gia_chuan_mau_melamine (stt, nguon, nhom, loai, ma_mau, vi_tri) VALUES (6, '220', 'Standard', 'Wood', '610', 9);
INSERT INTO bang_gia_chuan_mau_melamine (stt, nguon, nhom, loai, ma_mau, vi_tri) VALUES (6, '220', 'Standard', 'Art', '728', 10);
INSERT INTO bang_gia_chuan_mau_melamine (stt, nguon, nhom, loai, ma_mau, vi_tri) VALUES (6, '220', 'Standard', 'Color', '701', 11);
INSERT INTO bang_gia_chuan_mau_melamine (stt, nguon, nhom, loai, ma_mau, vi_tri) VALUES (6, '220', 'Premium', 'Wood', '322', 12);
INSERT INTO bang_gia_chuan_mau_melamine (stt, nguon, nhom, loai, ma_mau, vi_tri) VALUES (6, '220', 'Premium', 'Wood', '683', 13);
INSERT INTO bang_gia_chuan_mau_melamine (stt, nguon, nhom, loai, ma_mau, vi_tri) VALUES (6, '220', 'Premium', 'Wood', '789', 14);
INSERT INTO bang_gia_chuan_mau_melamine (stt, nguon, nhom, loai, ma_mau, vi_tri) VALUES (6, '220', 'Premium', 'Art', '521', 15);
INSERT INTO bang_gia_chuan_mau_melamine (stt, nguon, nhom, loai, ma_mau, vi_tri) VALUES (6, '220', 'Premium', 'Color', '984', 16);
INSERT INTO bang_gia_chuan_mau_melamine (stt, nguon, nhom, loai, ma_mau, vi_tri) VALUES (6, '220', 'Superb', 'Color', '050', 17);
INSERT INTO bang_gia_chuan_mau_melamine (stt, nguon, nhom, loai, ma_mau, vi_tri) VALUES (6, '220', 'Superb', 'Color', '216', 18);
INSERT INTO bang_gia_chuan_mau_melamine (stt, nguon, nhom, loai, ma_mau, vi_tri) VALUES (7, '220', 'Economy', 'Wood', '209', 1);
INSERT INTO bang_gia_chuan_mau_melamine (stt, nguon, nhom, loai, ma_mau, vi_tri) VALUES (7, '220', 'Economy', 'Wood', '333', 2);
INSERT INTO bang_gia_chuan_mau_melamine (stt, nguon, nhom, loai, ma_mau, vi_tri) VALUES (7, '220', 'Economy', 'Wood', '413', 3);
INSERT INTO bang_gia_chuan_mau_melamine (stt, nguon, nhom, loai, ma_mau, vi_tri) VALUES (7, '220', 'Economy', 'Wood', '434', 4);
INSERT INTO bang_gia_chuan_mau_melamine (stt, nguon, nhom, loai, ma_mau, vi_tri) VALUES (7, '220', 'Economy', 'Wood', '469', 5);
INSERT INTO bang_gia_chuan_mau_melamine (stt, nguon, nhom, loai, ma_mau, vi_tri) VALUES (7, '220', 'Economy', 'Wood', '622', 6);
INSERT INTO bang_gia_chuan_mau_melamine (stt, nguon, nhom, loai, ma_mau, vi_tri) VALUES (7, '220', 'Economy', 'Wood', '786', 7);
INSERT INTO bang_gia_chuan_mau_melamine (stt, nguon, nhom, loai, ma_mau, vi_tri) VALUES (7, '220', 'Standard', 'Wood', '446', 8);
INSERT INTO bang_gia_chuan_mau_melamine (stt, nguon, nhom, loai, ma_mau, vi_tri) VALUES (7, '220', 'Standard', 'Wood', '681', 9);
INSERT INTO bang_gia_chuan_mau_melamine (stt, nguon, nhom, loai, ma_mau, vi_tri) VALUES (7, '220', 'Standard', 'Art', '742', 10);
INSERT INTO bang_gia_chuan_mau_melamine (stt, nguon, nhom, loai, ma_mau, vi_tri) VALUES (7, '220', 'Standard', 'Color', '998', 11);
INSERT INTO bang_gia_chuan_mau_melamine (stt, nguon, nhom, loai, ma_mau, vi_tri) VALUES (7, '220', 'Premium', 'Color', '268', 12);
INSERT INTO bang_gia_chuan_mau_melamine (stt, nguon, nhom, loai, ma_mau, vi_tri) VALUES (7, '220', 'Premium', 'Wood', '319', 13);
INSERT INTO bang_gia_chuan_mau_melamine (stt, nguon, nhom, loai, ma_mau, vi_tri) VALUES (7, '220', 'Premium', 'Wood', '684', 14);
INSERT INTO bang_gia_chuan_mau_melamine (stt, nguon, nhom, loai, ma_mau, vi_tri) VALUES (7, '220', 'Premium', 'Wood', '902', 15);
INSERT INTO bang_gia_chuan_mau_melamine (stt, nguon, nhom, loai, ma_mau, vi_tri) VALUES (7, '220', 'Premium', 'Art', '581', 16);
INSERT INTO bang_gia_chuan_mau_melamine (stt, nguon, nhom, loai, ma_mau, vi_tri) VALUES (7, '220', 'Premium', 'Color', '702', 17);
INSERT INTO bang_gia_chuan_mau_melamine (stt, nguon, nhom, loai, ma_mau, vi_tri) VALUES (7, '220', 'Superb', 'Color', '051', 18);
INSERT INTO bang_gia_chuan_mau_melamine (stt, nguon, nhom, loai, ma_mau, vi_tri) VALUES (7, '220', 'Superb', 'Color', '219', 19);
INSERT INTO bang_gia_chuan_mau_melamine (stt, nguon, nhom, loai, ma_mau, vi_tri) VALUES (8, '220', 'Economy', 'Wood', '212', 1);
INSERT INTO bang_gia_chuan_mau_melamine (stt, nguon, nhom, loai, ma_mau, vi_tri) VALUES (8, '220', 'Economy', 'Wood', '335', 2);
INSERT INTO bang_gia_chuan_mau_melamine (stt, nguon, nhom, loai, ma_mau, vi_tri) VALUES (8, '220', 'Economy', 'Wood', '414', 3);
INSERT INTO bang_gia_chuan_mau_melamine (stt, nguon, nhom, loai, ma_mau, vi_tri) VALUES (8, '220', 'Economy', 'Wood', '435', 4);
INSERT INTO bang_gia_chuan_mau_melamine (stt, nguon, nhom, loai, ma_mau, vi_tri) VALUES (8, '220', 'Economy', 'Wood', '471', 5);
INSERT INTO bang_gia_chuan_mau_melamine (stt, nguon, nhom, loai, ma_mau, vi_tri) VALUES (8, '220', 'Economy', 'Wood', '642', 6);
INSERT INTO bang_gia_chuan_mau_melamine (stt, nguon, nhom, loai, ma_mau, vi_tri) VALUES (8, '220', 'Economy', 'Wood', '803', 7);
INSERT INTO bang_gia_chuan_mau_melamine (stt, nguon, nhom, loai, ma_mau, vi_tri) VALUES (8, '220', 'Standard', 'Wood', '452', 8);
INSERT INTO bang_gia_chuan_mau_melamine (stt, nguon, nhom, loai, ma_mau, vi_tri) VALUES (8, '220', 'Standard', 'Wood', '682', 9);
INSERT INTO bang_gia_chuan_mau_melamine (stt, nguon, nhom, loai, ma_mau, vi_tri) VALUES (8, '220', 'Standard', 'Art', '743', 10);
INSERT INTO bang_gia_chuan_mau_melamine (stt, nguon, nhom, loai, ma_mau, vi_tri) VALUES (8, '220', 'Premium', 'Wood', '350', 11);
INSERT INTO bang_gia_chuan_mau_melamine (stt, nguon, nhom, loai, ma_mau, vi_tri) VALUES (8, '220', 'Premium', 'Wood', '686', 12);
INSERT INTO bang_gia_chuan_mau_melamine (stt, nguon, nhom, loai, ma_mau, vi_tri) VALUES (8, '220', 'Premium', 'Wood', '960', 13);
INSERT INTO bang_gia_chuan_mau_melamine (stt, nguon, nhom, loai, ma_mau, vi_tri) VALUES (8, '220', 'Premium', 'Art', '585', 14);
INSERT INTO bang_gia_chuan_mau_melamine (stt, nguon, nhom, loai, ma_mau, vi_tri) VALUES (8, '220', 'Premium', 'Color', '703', 15);
INSERT INTO bang_gia_chuan_mau_melamine (stt, nguon, nhom, loai, ma_mau, vi_tri) VALUES (8, '220', 'Superb', 'Color', '052', 16);
INSERT INTO bang_gia_chuan_mau_melamine (stt, nguon, nhom, loai, ma_mau, vi_tri) VALUES (8, '220', 'Superb', 'Color', '222', 17);
INSERT INTO bang_gia_chuan_mau_melamine (stt, nguon, nhom, loai, ma_mau, vi_tri) VALUES (9, '220', 'Economy', 'Wood', '217', 1);
INSERT INTO bang_gia_chuan_mau_melamine (stt, nguon, nhom, loai, ma_mau, vi_tri) VALUES (9, '220', 'Economy', 'Wood', '337', 2);
INSERT INTO bang_gia_chuan_mau_melamine (stt, nguon, nhom, loai, ma_mau, vi_tri) VALUES (9, '220', 'Economy', 'Wood', '416', 3);
INSERT INTO bang_gia_chuan_mau_melamine (stt, nguon, nhom, loai, ma_mau, vi_tri) VALUES (9, '220', 'Economy', 'Wood', '436', 4);
INSERT INTO bang_gia_chuan_mau_melamine (stt, nguon, nhom, loai, ma_mau, vi_tri) VALUES (9, '220', 'Economy', 'Wood', '473', 5);
INSERT INTO bang_gia_chuan_mau_melamine (stt, nguon, nhom, loai, ma_mau, vi_tri) VALUES (9, '220', 'Economy', 'Wood', '668', 6);
INSERT INTO bang_gia_chuan_mau_melamine (stt, nguon, nhom, loai, ma_mau, vi_tri) VALUES (9, '220', 'Economy', 'Wood', '809', 7);
INSERT INTO bang_gia_chuan_mau_melamine (stt, nguon, nhom, loai, ma_mau, vi_tri) VALUES (9, '220', 'Standard', 'Wood', '463', 8);
INSERT INTO bang_gia_chuan_mau_melamine (stt, nguon, nhom, loai, ma_mau, vi_tri) VALUES (9, '220', 'Standard', 'Art', '744', 9);
INSERT INTO bang_gia_chuan_mau_melamine (stt, nguon, nhom, loai, ma_mau, vi_tri) VALUES (9, '220', 'Standard', 'Color', '458', 10);
INSERT INTO bang_gia_chuan_mau_melamine (stt, nguon, nhom, loai, ma_mau, vi_tri) VALUES (9, '220', 'Premium', 'Wood', '351', 11);
INSERT INTO bang_gia_chuan_mau_melamine (stt, nguon, nhom, loai, ma_mau, vi_tri) VALUES (9, '220', 'Premium', 'Wood', '689', 12);
INSERT INTO bang_gia_chuan_mau_melamine (stt, nguon, nhom, loai, ma_mau, vi_tri) VALUES (9, '220', 'Premium', 'Art', '533', 13);
INSERT INTO bang_gia_chuan_mau_melamine (stt, nguon, nhom, loai, ma_mau, vi_tri) VALUES (9, '220', 'Premium', 'Color', '704', 14);
INSERT INTO bang_gia_chuan_mau_melamine (stt, nguon, nhom, loai, ma_mau, vi_tri) VALUES (9, '220', 'Superb', 'Color', '026', 15);
INSERT INTO bang_gia_chuan_mau_melamine (stt, nguon, nhom, loai, ma_mau, vi_tri) VALUES (9, '220', 'Superb', 'Color', '224', 16);
INSERT INTO bang_gia_chuan_mau_melamine (stt, nguon, nhom, loai, ma_mau, vi_tri) VALUES (10, '220', 'Economy', 'Wood', '240', 1);
INSERT INTO bang_gia_chuan_mau_melamine (stt, nguon, nhom, loai, ma_mau, vi_tri) VALUES (10, '220', 'Economy', 'Wood', '338', 2);
INSERT INTO bang_gia_chuan_mau_melamine (stt, nguon, nhom, loai, ma_mau, vi_tri) VALUES (10, '220', 'Economy', 'Wood', '421', 3);
INSERT INTO bang_gia_chuan_mau_melamine (stt, nguon, nhom, loai, ma_mau, vi_tri) VALUES (10, '220', 'Economy', 'Wood', '440', 4);
INSERT INTO bang_gia_chuan_mau_melamine (stt, nguon, nhom, loai, ma_mau, vi_tri) VALUES (10, '220', 'Economy', 'Wood', '474', 5);
INSERT INTO bang_gia_chuan_mau_melamine (stt, nguon, nhom, loai, ma_mau, vi_tri) VALUES (10, '220', 'Economy', 'Wood', '861', 6);
INSERT INTO bang_gia_chuan_mau_melamine (stt, nguon, nhom, loai, ma_mau, vi_tri) VALUES (10, '220', 'Standard', 'Wood', '464', 7);
INSERT INTO bang_gia_chuan_mau_melamine (stt, nguon, nhom, loai, ma_mau, vi_tri) VALUES (10, '220', 'Standard', 'Art', '783', 8);
INSERT INTO bang_gia_chuan_mau_melamine (stt, nguon, nhom, loai, ma_mau, vi_tri) VALUES (10, '220', 'Premium', 'Wood', '360', 9);
INSERT INTO bang_gia_chuan_mau_melamine (stt, nguon, nhom, loai, ma_mau, vi_tri) VALUES (10, '220', 'Premium', 'Wood', 'Đ1', 10);
INSERT INTO bang_gia_chuan_mau_melamine (stt, nguon, nhom, loai, ma_mau, vi_tri) VALUES (10, '220', 'Premium', 'Art', '484', 11);
INSERT INTO bang_gia_chuan_mau_melamine (stt, nguon, nhom, loai, ma_mau, vi_tri) VALUES (10, '220', 'Premium', 'Color', '711', 12);
INSERT INTO bang_gia_chuan_mau_melamine (stt, nguon, nhom, loai, ma_mau, vi_tri) VALUES (10, '220', 'Superb', 'Color', '089', 13);
INSERT INTO bang_gia_chuan_mau_melamine (stt, nguon, nhom, loai, ma_mau, vi_tri) VALUES (10, '220', 'Superb', 'Color', '225', 14);
INSERT INTO bang_gia_chuan_mau_melamine (stt, nguon, nhom, loai, ma_mau, vi_tri) VALUES (11, '220', 'Economy', 'Wood', '340', 1);
INSERT INTO bang_gia_chuan_mau_melamine (stt, nguon, nhom, loai, ma_mau, vi_tri) VALUES (11, '220', 'Economy', 'Wood', '423', 2);
INSERT INTO bang_gia_chuan_mau_melamine (stt, nguon, nhom, loai, ma_mau, vi_tri) VALUES (11, '220', 'Economy', 'Wood', '442', 3);
INSERT INTO bang_gia_chuan_mau_melamine (stt, nguon, nhom, loai, ma_mau, vi_tri) VALUES (11, '220', 'Economy', 'Wood', '862', 4);
INSERT INTO bang_gia_chuan_mau_melamine (stt, nguon, nhom, loai, ma_mau, vi_tri) VALUES (11, '220', 'Standard', 'Wood', '468', 5);
INSERT INTO bang_gia_chuan_mau_melamine (stt, nguon, nhom, loai, ma_mau, vi_tri) VALUES (11, '220', 'Standard', 'Art', '810', 6);
INSERT INTO bang_gia_chuan_mau_melamine (stt, nguon, nhom, loai, ma_mau, vi_tri) VALUES (11, '220', 'Premium', 'Wood', '370', 7);
INSERT INTO bang_gia_chuan_mau_melamine (stt, nguon, nhom, loai, ma_mau, vi_tri) VALUES (11, '220', 'Premium', 'Art', '485', 8);
INSERT INTO bang_gia_chuan_mau_melamine (stt, nguon, nhom, loai, ma_mau, vi_tri) VALUES (11, '220', 'Premium', 'Color', '713', 9);
INSERT INTO bang_gia_chuan_mau_melamine (stt, nguon, nhom, loai, ma_mau, vi_tri) VALUES (11, '220', 'Superb', 'Color', '027', 10);
INSERT INTO bang_gia_chuan_mau_melamine (stt, nguon, nhom, loai, ma_mau, vi_tri) VALUES (11, '220', 'Superb', 'Color', '227', 11);
INSERT INTO bang_gia_chuan_mau_melamine (stt, nguon, nhom, loai, ma_mau, vi_tri) VALUES (12, '220', 'Economy', 'Wood', '376', 1);
INSERT INTO bang_gia_chuan_mau_melamine (stt, nguon, nhom, loai, ma_mau, vi_tri) VALUES (12, '220', 'Economy', 'Wood', '424', 2);
INSERT INTO bang_gia_chuan_mau_melamine (stt, nguon, nhom, loai, ma_mau, vi_tri) VALUES (12, '220', 'Economy', 'Wood', '443', 3);
INSERT INTO bang_gia_chuan_mau_melamine (stt, nguon, nhom, loai, ma_mau, vi_tri) VALUES (12, '220', 'Standard', 'Wood', '470', 4);
INSERT INTO bang_gia_chuan_mau_melamine (stt, nguon, nhom, loai, ma_mau, vi_tri) VALUES (12, '220', 'Premium', 'Wood', '387', 5);
INSERT INTO bang_gia_chuan_mau_melamine (stt, nguon, nhom, loai, ma_mau, vi_tri) VALUES (12, '220', 'Superb', 'Color', '228', 6);
-- bang_gia_chuan_go_ghep (5 rows)
INSERT INTO bang_gia_chuan_go_ghep (stt, quy_cach, cao_su_aa_ab, cao_su_ac, cao_su_bc, cao_su_cc, thong_nzl_aa) VALUES (1, '8mm', 550000, 485000, NULL, 360000, NULL);
INSERT INTO bang_gia_chuan_go_ghep (stt, quy_cach, cao_su_aa_ab, cao_su_ac, cao_su_bc, cao_su_cc, thong_nzl_aa) VALUES (2, '10mm', 570000, 505000, 475000, 380000, NULL);
INSERT INTO bang_gia_chuan_go_ghep (stt, quy_cach, cao_su_aa_ab, cao_su_ac, cao_su_bc, cao_su_cc, thong_nzl_aa) VALUES (3, '12mm', NULL, 530000, NULL, NULL, NULL);
INSERT INTO bang_gia_chuan_go_ghep (stt, quy_cach, cao_su_aa_ab, cao_su_ac, cao_su_bc, cao_su_cc, thong_nzl_aa) VALUES (4, '17mm', NULL, NULL, 610000, NULL, NULL);
INSERT INTO bang_gia_chuan_go_ghep (stt, quy_cach, cao_su_aa_ab, cao_su_ac, cao_su_bc, cao_su_cc, thong_nzl_aa) VALUES (5, '18mm', NULL, 645000, 620000, 565000, 740000);
-- bang_gia_chuan_phu_veneer (5 rows: 17-18mm đã tách thành 17mm + 18mm)
INSERT INTO bang_gia_chuan_phu_veneer (stt, quy_cach, xoan_1m, xoan_2m, soi_1m, soi_2m, soi_kt_1m, soi_kt_2m, oc_cho_kt_1m, oc_cho_kt_2m) VALUES (1, '8mm', NULL, 530000, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO bang_gia_chuan_phu_veneer (stt, quy_cach, xoan_1m, xoan_2m, soi_1m, soi_2m, soi_kt_1m, soi_kt_2m, oc_cho_kt_1m, oc_cho_kt_2m) VALUES (2, '10mm', 490000, 555000, 555000, 665000, 510000, 620000, 520000, 660000);
INSERT INTO bang_gia_chuan_phu_veneer (stt, quy_cach, xoan_1m, xoan_2m, soi_1m, soi_2m, soi_kt_1m, soi_kt_2m, oc_cho_kt_1m, oc_cho_kt_2m) VALUES (3, '12mm', 590000, NULL, NULL, 740000, NULL, NULL, NULL, NULL);
INSERT INTO bang_gia_chuan_phu_veneer (stt, quy_cach, xoan_1m, xoan_2m, soi_1m, soi_2m, soi_kt_1m, soi_kt_2m, oc_cho_kt_1m, oc_cho_kt_2m) VALUES (4, '17mm', 650000, 715000, 730000, 840000, 675000, 840000, NULL, 840000);
INSERT INTO bang_gia_chuan_phu_veneer (stt, quy_cach, xoan_1m, xoan_2m, soi_1m, soi_2m, soi_kt_1m, soi_kt_2m, oc_cho_kt_1m, oc_cho_kt_2m) VALUES (5, '18mm', 650000, 715000, 730000, 840000, 675000, 840000, NULL, 840000);
-- bang_gia_chuan_van_ep (9 rows)
INSERT INTO bang_gia_chuan_van_ep (stt, quy_cach, kt_1000x2000, kt_1220x2440) VALUES (1, '4mm', 102000, 144000);
INSERT INTO bang_gia_chuan_van_ep (stt, quy_cach, kt_1000x2000, kt_1220x2440) VALUES (2, '5mm', NULL, 204000);
INSERT INTO bang_gia_chuan_van_ep (stt, quy_cach, kt_1000x2000, kt_1220x2440) VALUES (3, '6mm', 149000, 232000);
INSERT INTO bang_gia_chuan_van_ep (stt, quy_cach, kt_1000x2000, kt_1220x2440) VALUES (4, '8mm', 149000, 232000);
INSERT INTO bang_gia_chuan_van_ep (stt, quy_cach, kt_1000x2000, kt_1220x2440) VALUES (5, '10mm', 176000, 269000);
INSERT INTO bang_gia_chuan_van_ep (stt, quy_cach, kt_1000x2000, kt_1220x2440) VALUES (6, '12mm', 200000, 292000);
INSERT INTO bang_gia_chuan_van_ep (stt, quy_cach, kt_1000x2000, kt_1220x2440) VALUES (7, '14mm', 223000, 343000);
INSERT INTO bang_gia_chuan_van_ep (stt, quy_cach, kt_1000x2000, kt_1220x2440) VALUES (8, '16mm', 246000, 371000);
INSERT INTO bang_gia_chuan_van_ep (stt, quy_cach, kt_1000x2000, kt_1220x2440) VALUES (9, '18mm', 269000, 408000);
-- bang_gia_chuan_van_ep_khac (19 rows)
INSERT INTO bang_gia_chuan_van_ep_khac (stt, quy_cach, loai, gia, nhom) VALUES (1, '3mm', 'POPLAR AA', 190000, 'Nhập khẩu');
INSERT INTO bang_gia_chuan_van_ep_khac (stt, quy_cach, loai, gia, nhom) VALUES (2, '5mm', 'POPLAR AA', 320000, 'Nhập khẩu');
INSERT INTO bang_gia_chuan_van_ep_khac (stt, quy_cach, loai, gia, nhom) VALUES (2, '5mm', 'EV/EV', 450000, 'Nhập khẩu');
INSERT INTO bang_gia_chuan_van_ep_khac (stt, quy_cach, loai, gia, nhom) VALUES (3, '9mm', 'BIRCH C/D', 542000, 'Nhập khẩu');
INSERT INTO bang_gia_chuan_van_ep_khac (stt, quy_cach, loai, gia, nhom) VALUES (3, '9mm', 'POPLAR AA', 440000, 'Nhập khẩu');
INSERT INTO bang_gia_chuan_van_ep_khac (stt, quy_cach, loai, gia, nhom) VALUES (4, '12mm', 'BIRCH C/D', 663000, 'Nhập khẩu');
INSERT INTO bang_gia_chuan_van_ep_khac (stt, quy_cach, loai, gia, nhom) VALUES (4, '12mm', 'POPLAR AA', 542000, 'Nhập khẩu');
INSERT INTO bang_gia_chuan_van_ep_khac (stt, quy_cach, loai, gia, nhom) VALUES (5, '15mm', 'POPLAR AA', 653000, 'Nhập khẩu');
INSERT INTO bang_gia_chuan_van_ep_khac (stt, quy_cach, loai, gia, nhom) VALUES (6, '18mm', 'BIRCH C/D', 913000, 'Nhập khẩu');
INSERT INTO bang_gia_chuan_van_ep_khac (stt, quy_cach, loai, gia, nhom) VALUES (6, '18mm', 'POPLAR AA', 755000, 'Nhập khẩu');
INSERT INTO bang_gia_chuan_van_ep_khac (stt, quy_cach, loai, gia, nhom) VALUES (6, '18mm', 'EV/EV', 806000, 'Nhập khẩu');
INSERT INTO bang_gia_chuan_van_ep_khac (stt, quy_cach, loai, gia, nhom) VALUES (7, '25mm', 'EV/EV', 1204000, 'Nhập khẩu');
INSERT INTO bang_gia_chuan_van_ep_khac (stt, quy_cach, loai, gia, nhom) VALUES (1, '17mm', 'Standard', 490000, 'Phủ phim');
INSERT INTO bang_gia_chuan_van_ep_khac (stt, quy_cach, loai, gia, nhom) VALUES (2, '18mm', 'Standard', 490000, 'Phủ phim');
INSERT INTO bang_gia_chuan_van_ep_khac (stt, quy_cach, loai, gia, nhom) VALUES (1, '18mm', 'Sồi KT', 825000, 'Phủ veneer');
INSERT INTO bang_gia_chuan_van_ep_khac (stt, quy_cach, loai, gia, nhom) VALUES (1, '18mm', 'Walnut KT', 875000, 'Phủ veneer');
INSERT INTO bang_gia_chuan_van_ep_khac (stt, quy_cach, loai, gia, nhom) VALUES (2, '9mm', 'Sồi KT', 600000, 'Phủ veneer');
INSERT INTO bang_gia_chuan_van_ep_khac (stt, quy_cach, loai, gia, nhom) VALUES (2, '9mm', 'Walnut KT', 650000, 'Phủ veneer');
INSERT INTO bang_gia_chuan_van_ep_khac (stt, quy_cach, loai, gia, nhom) VALUES (1, '18mm', 'Giá lẻ', 600000, 'Okume/EV');
INSERT INTO bang_gia_chuan_van_ep_khac (stt, quy_cach, loai, gia, nhom) VALUES (2, '8-9mm', 'Giá lẻ', 330000, 'Okume/EV');
-- bang_gia_chuan_pvc_film_dura (32 rows)
INSERT INTO bang_gia_chuan_pvc_film_dura (ma_mau, nhom, loai, thong_so) VALUES ('NW 06', 'Ưu đãi', 'PVC film', '0.14~0.16mm');
INSERT INTO bang_gia_chuan_pvc_film_dura (ma_mau, nhom, loai, thong_so) VALUES ('NW 07', 'Ưu đãi', 'PVC film', '0.14~0.16mm');
INSERT INTO bang_gia_chuan_pvc_film_dura (ma_mau, nhom, loai, thong_so) VALUES ('NW 10', 'Ưu đãi', 'PVC film', '0.14~0.16mm');
INSERT INTO bang_gia_chuan_pvc_film_dura (ma_mau, nhom, loai, thong_so) VALUES ('NW 11', 'Ưu đãi', 'PVC film', '0.14~0.16mm');
INSERT INTO bang_gia_chuan_pvc_film_dura (ma_mau, nhom, loai, thong_so) VALUES ('NW 35', 'Ưu đãi', 'PVC film', '0.14~0.16mm');
INSERT INTO bang_gia_chuan_pvc_film_dura (ma_mau, nhom, loai, thong_so) VALUES ('NW 39', 'Ưu đãi', 'PVC film', '0.14~0.16mm');
INSERT INTO bang_gia_chuan_pvc_film_dura (ma_mau, nhom, loai, thong_so) VALUES ('PW 21', 'Ưu đãi', 'PVC film', '0.14~0.16mm');
INSERT INTO bang_gia_chuan_pvc_film_dura (ma_mau, nhom, loai, thong_so) VALUES ('NW 01', 'Standard', 'PVC film', '0.14~0.16mm');
INSERT INTO bang_gia_chuan_pvc_film_dura (ma_mau, nhom, loai, thong_so) VALUES ('NW 02', 'Standard', 'PVC film', '0.14~0.16mm');
INSERT INTO bang_gia_chuan_pvc_film_dura (ma_mau, nhom, loai, thong_so) VALUES ('NW 03', 'Standard', 'PVC film', '0.14~0.16mm');
INSERT INTO bang_gia_chuan_pvc_film_dura (ma_mau, nhom, loai, thong_so) VALUES ('NW 04', 'Standard', 'PVC film', '0.14~0.16mm');
INSERT INTO bang_gia_chuan_pvc_film_dura (ma_mau, nhom, loai, thong_so) VALUES ('NW 05', 'Standard', 'PVC film', '0.14~0.16mm');
INSERT INTO bang_gia_chuan_pvc_film_dura (ma_mau, nhom, loai, thong_so) VALUES ('NW 08', 'Standard', 'PVC film', '0.14~0.16mm');
INSERT INTO bang_gia_chuan_pvc_film_dura (ma_mau, nhom, loai, thong_so) VALUES ('NW 09', 'Standard', 'PVC film', '0.14~0.16mm');
INSERT INTO bang_gia_chuan_pvc_film_dura (ma_mau, nhom, loai, thong_so) VALUES ('NW 12', 'Standard', 'PVC film', '0.14~0.16mm');
INSERT INTO bang_gia_chuan_pvc_film_dura (ma_mau, nhom, loai, thong_so) VALUES ('NW 13', 'Standard', 'PVC film', '0.14~0.16mm');
INSERT INTO bang_gia_chuan_pvc_film_dura (ma_mau, nhom, loai, thong_so) VALUES ('NW 15', 'Standard', 'PVC film', '0.14~0.16mm');
INSERT INTO bang_gia_chuan_pvc_film_dura (ma_mau, nhom, loai, thong_so) VALUES ('NW 34', 'Standard', 'PVC film', '0.14~0.16mm');
INSERT INTO bang_gia_chuan_pvc_film_dura (ma_mau, nhom, loai, thong_so) VALUES ('NW 36', 'Standard', 'PVC film', '0.14~0.16mm');
INSERT INTO bang_gia_chuan_pvc_film_dura (ma_mau, nhom, loai, thong_so) VALUES ('NW 37', 'Standard', 'PVC film', '0.14~0.16mm');
INSERT INTO bang_gia_chuan_pvc_film_dura (ma_mau, nhom, loai, thong_so) VALUES ('NS 27', 'Standard', 'PVC film', '0.14~0.16mm');
INSERT INTO bang_gia_chuan_pvc_film_dura (ma_mau, nhom, loai, thong_so) VALUES ('NS 28', 'Standard', 'PVC film', '0.14~0.16mm');
INSERT INTO bang_gia_chuan_pvc_film_dura (ma_mau, nhom, loai, thong_so) VALUES ('NS 30', 'Standard', 'PVC film', '0.14~0.16mm');
INSERT INTO bang_gia_chuan_pvc_film_dura (ma_mau, nhom, loai, thong_so) VALUES ('NS 40', 'Standard', 'PVC film', '0.14~0.16mm');
INSERT INTO bang_gia_chuan_pvc_film_dura (ma_mau, nhom, loai, thong_so) VALUES ('NS 41', 'Standard', 'PVC film', '0.14~0.16mm');
INSERT INTO bang_gia_chuan_pvc_film_dura (ma_mau, nhom, loai, thong_so) VALUES ('NM 38', 'Standard', 'PVC film', '0.14~0.16mm');
INSERT INTO bang_gia_chuan_pvc_film_dura (ma_mau, nhom, loai, thong_so) VALUES ('PW 20', 'Premium', 'PVC film', '0.14~0.16mm');
INSERT INTO bang_gia_chuan_pvc_film_dura (ma_mau, nhom, loai, thong_so) VALUES ('PW 24', 'Premium', 'PVC film', '0.14~0.16mm');
INSERT INTO bang_gia_chuan_pvc_film_dura (ma_mau, nhom, loai, thong_so) VALUES ('PM 33', 'Premium', 'PVC film', '0.14~0.16mm');
INSERT INTO bang_gia_chuan_pvc_film_dura (ma_mau, nhom, loai, thong_so) VALUES ('SS 18', 'PETG', 'PETG', '0.45mm');
INSERT INTO bang_gia_chuan_pvc_film_dura (ma_mau, nhom, loai, thong_so) VALUES ('SS28', 'PETG', 'PETG', '0.45mm');
INSERT INTO bang_gia_chuan_pvc_film_dura (ma_mau, nhom, loai, thong_so) VALUES ('SS38', 'PETG', 'PETG', '0.45mm');
-- bang_gia_chuan_van_phu_pvc_petg (14 rows)
INSERT INTO bang_gia_chuan_van_phu_pvc_petg (stt, loai_van, do_day, gia_uu_dai_1m, gia_uu_dai_2m, gia_standard_1m, gia_standard_2m, gia_premium_1m, gia_premium_2m, gia_petg_1m, gia_petg_2m) VALUES (1, 'DURABO 0.6', '5mm', 387000, 554000, 406000, 592000, 452000, 684000, 591000, 962000);
INSERT INTO bang_gia_chuan_van_phu_pvc_petg (stt, loai_van, do_day, gia_uu_dai_1m, gia_uu_dai_2m, gia_standard_1m, gia_standard_2m, gia_premium_1m, gia_premium_2m, gia_petg_1m, gia_petg_2m) VALUES (2, 'DURABO 0.6', '8mm', 512000, 679000, 531000, 717000, 577000, 809000, 716000, 1087000);
INSERT INTO bang_gia_chuan_van_phu_pvc_petg (stt, loai_van, do_day, gia_uu_dai_1m, gia_uu_dai_2m, gia_standard_1m, gia_standard_2m, gia_premium_1m, gia_premium_2m, gia_petg_1m, gia_petg_2m) VALUES (3, 'DURABO 0.6', '12mm', 697000, 864000, 716000, 902000, 762000, 994000, 901000, 1272000);
INSERT INTO bang_gia_chuan_van_phu_pvc_petg (stt, loai_van, do_day, gia_uu_dai_1m, gia_uu_dai_2m, gia_standard_1m, gia_standard_2m, gia_premium_1m, gia_premium_2m, gia_petg_1m, gia_petg_2m) VALUES (4, 'DURABO 0.6', '17mm', 902000, 1069000, 921000, 1107000, 967000, 1199000, 1106000, 1477000);
INSERT INTO bang_gia_chuan_van_phu_pvc_petg (stt, loai_van, do_day, gia_uu_dai_1m, gia_uu_dai_2m, gia_standard_1m, gia_standard_2m, gia_premium_1m, gia_premium_2m, gia_petg_1m, gia_petg_2m) VALUES (5, 'DURABO 0.55', '5mm', 367000, 534000, 386000, 572000, 432000, 664000, 571000, 942000);
INSERT INTO bang_gia_chuan_van_phu_pvc_petg (stt, loai_van, do_day, gia_uu_dai_1m, gia_uu_dai_2m, gia_standard_1m, gia_standard_2m, gia_premium_1m, gia_premium_2m, gia_petg_1m, gia_petg_2m) VALUES (6, 'DURABO 0.55', '8mm', 487000, 654000, 506000, 692000, 552000, 784000, 691000, 1062000);
INSERT INTO bang_gia_chuan_van_phu_pvc_petg (stt, loai_van, do_day, gia_uu_dai_1m, gia_uu_dai_2m, gia_standard_1m, gia_standard_2m, gia_premium_1m, gia_premium_2m, gia_petg_1m, gia_petg_2m) VALUES (7, 'DURABO 0.55', '12mm', 647000, 814000, 666000, 852000, 712000, 944000, 851000, 1222000);
INSERT INTO bang_gia_chuan_van_phu_pvc_petg (stt, loai_van, do_day, gia_uu_dai_1m, gia_uu_dai_2m, gia_standard_1m, gia_standard_2m, gia_premium_1m, gia_premium_2m, gia_petg_1m, gia_petg_2m) VALUES (8, 'DURABO 0.5', '17mm', 837000, 1004000, 856000, 1042000, 902000, 1134000, 1041000, 1412000);
INSERT INTO bang_gia_chuan_van_phu_pvc_petg (stt, loai_van, do_day, gia_uu_dai_1m, gia_uu_dai_2m, gia_standard_1m, gia_standard_2m, gia_premium_1m, gia_premium_2m, gia_petg_1m, gia_petg_2m) VALUES (9, 'Ván nhựa than tre 0.65', '8mm', 567000, 734000, 586000, 772000, 632000, 864000, 771000, 1142000);
INSERT INTO bang_gia_chuan_van_phu_pvc_petg (stt, loai_van, do_day, gia_uu_dai_1m, gia_uu_dai_2m, gia_standard_1m, gia_standard_2m, gia_premium_1m, gia_premium_2m, gia_petg_1m, gia_petg_2m) VALUES (10, 'Ván nhựa than tre 0.65', '17mm', 857000, 1024000, 876000, 1062000, 922000, 1154000, 1061000, 1432000);
INSERT INTO bang_gia_chuan_van_phu_pvc_petg (stt, loai_van, do_day, gia_uu_dai_1m, gia_uu_dai_2m, gia_standard_1m, gia_standard_2m, gia_premium_1m, gia_premium_2m, gia_petg_1m, gia_petg_2m) VALUES (11, 'MDF thường', '8mm', 342000, 509000, 361000, 547000, 407000, 639000, 546000, 917000);
INSERT INTO bang_gia_chuan_van_phu_pvc_petg (stt, loai_van, do_day, gia_uu_dai_1m, gia_uu_dai_2m, gia_standard_1m, gia_standard_2m, gia_premium_1m, gia_premium_2m, gia_petg_1m, gia_petg_2m) VALUES (12, 'MDF thường', '17mm', 505000, 672000, 524000, 710000, 570000, 802000, 709000, 1080000);
INSERT INTO bang_gia_chuan_van_phu_pvc_petg (stt, loai_van, do_day, gia_uu_dai_1m, gia_uu_dai_2m, gia_standard_1m, gia_standard_2m, gia_premium_1m, gia_premium_2m, gia_petg_1m, gia_petg_2m) VALUES (13, 'MDF kháng ẩm VN', '8mm', 362000, 529000, 381000, 567000, 427000, 659000, 566000, 937000);
INSERT INTO bang_gia_chuan_van_phu_pvc_petg (stt, loai_van, do_day, gia_uu_dai_1m, gia_uu_dai_2m, gia_standard_1m, gia_standard_2m, gia_premium_1m, gia_premium_2m, gia_petg_1m, gia_petg_2m) VALUES (14, 'MDF kháng ẩm VN', '17mm', 535000, 702000, 554000, 740000, 600000, 832000, 739000, 1110000);
-- bang_gia_chuan_durabo (36 rows)
INSERT INTO bang_gia_chuan_durabo (stt, quy_cach, loai, nhom, gia, dong_goi) VALUES (1, '3mm', '0.32–0.37D ko BH', 'DURABO ECO', 93000, '12');
INSERT INTO bang_gia_chuan_durabo (stt, quy_cach, loai, nhom, gia, dong_goi) VALUES (2, '5mm', '0.32–0.37D ko BH', 'DURABO ECO', 150000, '10');
INSERT INTO bang_gia_chuan_durabo (stt, quy_cach, loai, nhom, gia, dong_goi) VALUES (3, '8mm', '0.32–0.37D ko BH', 'DURABO ECO', 238000, '5');
INSERT INTO bang_gia_chuan_durabo (stt, quy_cach, loai, nhom, gia, dong_goi) VALUES (4, '5mm', 'DURABO 0.55D', 'DURABO', 200000, NULL);
INSERT INTO bang_gia_chuan_durabo (stt, quy_cach, loai, nhom, gia, dong_goi) VALUES (5, '8mm', 'DURABO 0.6D', 'DURABO', 345000, NULL);
INSERT INTO bang_gia_chuan_durabo (stt, quy_cach, loai, nhom, gia, dong_goi) VALUES (6, '8mm', 'DURABO 0.55D', 'DURABO', 320000, NULL);
INSERT INTO bang_gia_chuan_durabo (stt, quy_cach, loai, nhom, gia, dong_goi) VALUES (7, '8mm', 'Siêu bóng 2 mặt', 'DURABO', 520000, NULL);
INSERT INTO bang_gia_chuan_durabo (stt, quy_cach, loai, nhom, gia, dong_goi) VALUES (8, '9mm', 'DURABO 0.5D ko BH', 'DURABO', 360000, NULL);
INSERT INTO bang_gia_chuan_durabo (stt, quy_cach, loai, nhom, gia, dong_goi) VALUES (9, '10mm', 'DURABO 0.6D', 'DURABO', 440000, NULL);
INSERT INTO bang_gia_chuan_durabo (stt, quy_cach, loai, nhom, gia, dong_goi) VALUES (10, '10mm', 'DURABO 0.55D', 'DURABO', 400000, NULL);
INSERT INTO bang_gia_chuan_durabo (stt, quy_cach, loai, nhom, gia, dong_goi) VALUES (11, '12mm', 'DURABO 0.6D', 'DURABO', 530000, NULL);
INSERT INTO bang_gia_chuan_durabo (stt, quy_cach, loai, nhom, gia, dong_goi) VALUES (12, '12mm', 'DURABO 0.55D', 'DURABO', 480000, NULL);
INSERT INTO bang_gia_chuan_durabo (stt, quy_cach, loai, nhom, gia, dong_goi) VALUES (13, '15mm', 'DURABO 0.55D', 'DURABO', 600000, NULL);
INSERT INTO bang_gia_chuan_durabo (stt, quy_cach, loai, nhom, gia, dong_goi) VALUES (14, '15mm', 'DURABO 0.5D ko BH', 'DURABO', 550000, NULL);
INSERT INTO bang_gia_chuan_durabo (stt, quy_cach, loai, nhom, gia, dong_goi) VALUES (15, '17mm', 'DURABO 0.6D', 'DURABO', 735000, NULL);
INSERT INTO bang_gia_chuan_durabo (stt, quy_cach, loai, nhom, gia, dong_goi) VALUES (16, '17mm', 'DURABO 0.55D', 'DURABO', 670000, NULL);
INSERT INTO bang_gia_chuan_durabo (stt, quy_cach, loai, nhom, gia, dong_goi) VALUES (17, '17mm', 'DURABO 0.5D ko BH', 'DURABO', 620000, NULL);
INSERT INTO bang_gia_chuan_durabo (stt, quy_cach, loai, nhom, gia, dong_goi) VALUES (18, '17mm', 'Siêu bóng 1 mặt', 'DURABO', 830000, NULL);
INSERT INTO bang_gia_chuan_durabo (stt, quy_cach, loai, nhom, gia, dong_goi) VALUES (19, '17mm', 'Siêu bóng 2 mặt', 'DURABO', 880000, NULL);
INSERT INTO bang_gia_chuan_durabo (stt, quy_cach, loai, nhom, gia, dong_goi) VALUES (20, '5mm', 'Celuka Trắng 0.6D', 'Ván nhựa', 220000, NULL);
INSERT INTO bang_gia_chuan_durabo (stt, quy_cach, loai, nhom, gia, dong_goi) VALUES (21, '5mm', 'Celuka Trắng 0.55D', 'Ván nhựa', 200000, NULL);
INSERT INTO bang_gia_chuan_durabo (stt, quy_cach, loai, nhom, gia, dong_goi) VALUES (22, '8mm', 'Celuka Trắng 0.6D', 'Ván nhựa', 345000, NULL);
INSERT INTO bang_gia_chuan_durabo (stt, quy_cach, loai, nhom, gia, dong_goi) VALUES (23, '8mm', 'Celuka Trắng 0.55D', 'Ván nhựa', 320000, NULL);
INSERT INTO bang_gia_chuan_durabo (stt, quy_cach, loai, nhom, gia, dong_goi) VALUES (24, '8mm', 'Co-extrusion lõi đen', 'Ván nhựa', 400000, NULL);
INSERT INTO bang_gia_chuan_durabo (stt, quy_cach, loai, nhom, gia, dong_goi) VALUES (25, '10mm', 'Celuka Trắng 0.6D', 'Ván nhựa', 440000, NULL);
INSERT INTO bang_gia_chuan_durabo (stt, quy_cach, loai, nhom, gia, dong_goi) VALUES (26, '10mm', 'Celuka Trắng 0.55D', 'Ván nhựa', 400000, NULL);
INSERT INTO bang_gia_chuan_durabo (stt, quy_cach, loai, nhom, gia, dong_goi) VALUES (27, '12mm', 'Celuka Trắng 0.6D', 'Ván nhựa', 530000, NULL);
INSERT INTO bang_gia_chuan_durabo (stt, quy_cach, loai, nhom, gia, dong_goi) VALUES (28, '12mm', 'Celuka Trắng 0.55D', 'Ván nhựa', 480000, NULL);
INSERT INTO bang_gia_chuan_durabo (stt, quy_cach, loai, nhom, gia, dong_goi) VALUES (29, '15mm', 'Celuka Trắng 0.6D', 'Ván nhựa', 650000, NULL);
INSERT INTO bang_gia_chuan_durabo (stt, quy_cach, loai, nhom, gia, dong_goi) VALUES (30, '15mm', 'Celuka Trắng 0.55D', 'Ván nhựa', 600000, NULL);
INSERT INTO bang_gia_chuan_durabo (stt, quy_cach, loai, nhom, gia, dong_goi) VALUES (31, '17mm', 'Celuka Trắng 0.6D', 'Ván nhựa', 735000, NULL);
INSERT INTO bang_gia_chuan_durabo (stt, quy_cach, loai, nhom, gia, dong_goi) VALUES (32, '17mm', 'Celuka Trắng 0.55D', 'Ván nhựa', 670000, NULL);
INSERT INTO bang_gia_chuan_durabo (stt, quy_cach, loai, nhom, gia, dong_goi) VALUES (33, '17mm', 'Co-extrusion lõi đen', 'Ván nhựa', 690000, NULL);
INSERT INTO bang_gia_chuan_durabo (stt, quy_cach, loai, nhom, gia, dong_goi) VALUES (34, '17mm', 'Co-extrusion lõi trắng', 'Ván nhựa', 834000, NULL);
INSERT INTO bang_gia_chuan_durabo (stt, quy_cach, loai, nhom, gia, dong_goi) VALUES (35, '17mm', 'WPC Shield Board 0.6D', 'Ván nhựa', 865000, NULL);
INSERT INTO bang_gia_chuan_durabo (stt, quy_cach, loai, nhom, gia, dong_goi) VALUES (36, '17mm', 'WPC Shield Board 0.6D (nhóm 2)', 'Ván nhựa', 902000, NULL);
-- bang_gia_chuan_osb (5 rows)
INSERT INTO bang_gia_chuan_osb (stt, mo_ta, do_day, gia, gia_da_ck_10, gia_da_ck_15, gia_chua_ck_10, gia_chua_ck_15, tam_kien) VALUES (1, 'OSB 2 (E2) mặt mix, nhám, sử dụng làm sàn, vách, đóng thùng bao bì, vv', '8-9mm', 240000, 216000, 204000, 237600, 224400, 110);
INSERT INTO bang_gia_chuan_osb (stt, mo_ta, do_day, gia, gia_da_ck_10, gia_da_ck_15, gia_chua_ck_10, gia_chua_ck_15, tam_kien) VALUES (0, 'OSB 2 (E2) mặt mix, nhám, sử dụng làm sàn, vách, đóng thùng bao bì, vv', '17-18mm', 410000, 369000, 348500, 405900, 383350, 55);
INSERT INTO bang_gia_chuan_osb (stt, mo_ta, do_day, gia, gia_da_ck_10, gia_da_ck_15, gia_chua_ck_10, gia_chua_ck_15, tam_kien) VALUES (2, 'OSB (E0) gỗ thông (Full pine)', '9mm', 310000, 279000, 263500, 306900, 289850, 110);
INSERT INTO bang_gia_chuan_osb (stt, mo_ta, do_day, gia, gia_da_ck_10, gia_da_ck_15, gia_chua_ck_10, gia_chua_ck_15, tam_kien) VALUES (0, 'OSB (E0) gỗ thông (Full pine)', '12mm', 450000, 405000, 382500, 445500, 420750, 80);
INSERT INTO bang_gia_chuan_osb (stt, mo_ta, do_day, gia, gia_da_ck_10, gia_da_ck_15, gia_chua_ck_10, gia_chua_ck_15, tam_kien) VALUES (0, 'OSB (E0) gỗ thông (Full pine)', '18mm', 570000, 513000, 484500, 564300, 532950, 50);
-- bang_gia_chuan_mau_melamine_2 (216 rows)
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('184', 'SÁNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('421', 'SÁNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('D3', 'SÁNG', 'ĐÁ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('0029', 'TRUNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('380', 'TRUNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('439', 'TRUNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('474', 'TRUNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('609', 'TRUNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('742', 'TRUNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('D1', 'TRUNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('711', 'TRUNG', 'ART');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('D2', 'TRUNG', 'ĐÁ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('0446', 'TRUNG', 'VẢI');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('132', 'TỐI', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('414', 'TỐI', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('D4', 'TỐI', 'ĐÁ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('702', 'TỐI', 'VẢI');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('021', 'ĐƠN SẮC', 'ĐƠN SẮC');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('200', 'ĐƠN SẮC', 'ĐƠN SẮC');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('217', 'SÁNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('424', 'SÁNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('D5', 'SÁNG', 'ĐÁ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('142', 'TRUNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('385', 'TRUNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('440', 'TRUNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('484', 'TRUNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('612', 'TRUNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('750', 'TRUNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('4028', 'TRUNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('713', 'TRUNG', 'ART');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('D7', 'TRUNG', 'ĐÁ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('701', 'TRUNG', 'VẢI');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('136', 'TỐI', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('423', 'TỐI', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('D8', 'TỐI', 'ĐÁ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('041', 'ĐƠN SẮC', 'ĐƠN SẮC');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('025', 'ĐƠN SẮC', 'ĐƠN SẮC');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('240', 'SÁNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('429', 'SÁNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('D6', 'SÁNG', 'ĐÁ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('145', 'TRUNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('386', 'TRUNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('443', 'TRUNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('485', 'TRUNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('642', 'TRUNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('757', 'TRUNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('4029', 'TRUNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('901', 'TRUNG', 'ĐÁ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('703', 'TRUNG', 'VẢI');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('139', 'TỐI', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('442', 'TỐI', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('030', 'ĐƠN SẮC', 'ĐƠN SẮC');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('0212', 'ĐƠN SẮC', 'ĐƠN SẮC');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('301', 'SÁNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('452', 'SÁNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('D9', 'SÁNG', 'ĐÁ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('201', 'TRUNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('387', 'TRUNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('444', 'TRUNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('502', 'TRUNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('668', 'TRUNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('776', 'TRUNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('4030', 'TRUNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('D10', 'TRUNG', 'ĐÁ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('704', 'TRUNG', 'VẢI');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('161', 'TỐI', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('530', 'TỐI', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('220', 'ĐƠN SẮC', 'ĐƠN SẮC');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('213', 'ĐƠN SẮC', 'ĐƠN SẮC');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('311', 'SÁNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('468', 'SÁNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('D11', 'SÁNG', 'ĐÁ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('209', 'TRUNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('404', 'TRUNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('445', 'TRUNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('503', 'TRUNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('682', 'TRUNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('783', 'TRUNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('4457', 'TRUNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('430', 'TRUNG', 'ĐÁ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('998', 'TRUNG', 'VẢI');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('268', 'TỐI', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('556', 'TỐI', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('073', 'ĐƠN SẮC', 'ĐƠN SẮC');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('215', 'ĐƠN SẮC', 'ĐƠN SẮC');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('319', 'SÁNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('501', 'SÁNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('212', 'TRUNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('405', 'TRUNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('446', 'TRUNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('521', 'TRUNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('683', 'TRUNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('786', 'TRUNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('0439', 'TRUNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('431', 'TRUNG', 'ĐÁ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('303', 'TỐI', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('590', 'TỐI', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('051', 'ĐƠN SẮC', 'ĐƠN SẮC');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('216', 'ĐƠN SẮC', 'ĐƠN SẮC');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('320', 'SÁNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('504', 'SÁNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('23015', 'TRUNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('407', 'TRUNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('447', 'TRUNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('524', 'TRUNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('684', 'TRUNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('787', 'TRUNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('0330', 'TRUNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('458', 'TRUNG', 'ĐÁ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('312', 'TỐI', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('601', 'TỐI', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('050', 'ĐƠN SẮC', 'ĐƠN SẮC');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('219', 'ĐƠN SẮC', 'ĐƠN SẮC');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('321', 'SÁNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('610', 'SÁNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('330', 'TRUNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('416', 'TRUNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('448', 'TRUNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('533', 'TRUNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('686', 'TRUNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('789', 'TRUNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('984', 'TRUNG', 'ĐÁ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('302', 'TỐI', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('613', 'TỐI', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('052', 'ĐƠN SẮC', 'ĐƠN SẮC');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('104', 'ĐƠN SẮC', 'ĐƠN SẮC');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('325', 'SÁNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('611', 'SÁNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('331', 'TRUNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('425', 'TRUNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('460', 'TRUNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('541', 'TRUNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('689', 'TRUNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('809', 'TRUNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('322', 'TỐI', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('614', 'TỐI', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('026', 'ĐƠN SẮC', 'ĐƠN SẮC');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('106', 'ĐƠN SẮC', 'ĐƠN SẮC');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('388', 'SÁNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('621', 'SÁNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('332', 'TRUNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('426', 'TRUNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('463', 'TRUNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('545', 'TRUNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('714', 'TRUNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('810', 'TRUNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('329', 'TỐI', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('719', 'TỐI', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('089', 'ĐƠN SẮC', 'ĐƠN SẮC');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('033', 'ĐƠN SẮC', 'ĐƠN SẮC');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('389', 'SÁNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('622', 'SÁNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('335', 'TRUNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('427', 'TRUNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('464', 'TRUNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('551', 'TRUNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('722', 'TRUNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('862', 'TRUNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('333', 'TỐI', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('725', 'TỐI', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('027', 'ĐƠN SẮC', 'ĐƠN SẮC');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('034', 'ĐƠN SẮC', 'ĐƠN SẮC');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('402', 'SÁNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('681', 'SÁNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('337', 'TRUNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('428', 'TRUNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('467', 'TRUNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('571', 'TRUNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('728', 'TRUNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('902', 'TRUNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('336', 'TỐI', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('735', 'TỐI', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('203', 'ĐƠN SẮC', 'ĐƠN SẮC');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('222', 'ĐƠN SẮC', 'ĐƠN SẮC');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('403', 'SÁNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('708', 'SÁNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('340', 'TRUNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('432', 'TRUNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('469', 'TRUNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('572', 'TRUNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('736', 'TRUNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('960', 'TRUNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('338', 'TỐI', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('743', 'TỐI', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('100', 'ĐƠN SẮC', 'ĐƠN SẮC');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('224', 'ĐƠN SẮC', 'ĐƠN SẮC');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('410', 'SÁNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('740', 'SÁNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('350', 'TRUNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('434', 'TRUNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('470', 'TRUNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('577', 'TRUNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('737', 'TRUNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('370', 'TỐI', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('744', 'TỐI', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('230', 'ĐƠN SẮC', 'ĐƠN SẮC');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('226', 'ĐƠN SẮC', 'ĐƠN SẮC');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('412', 'SÁNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('759', 'SÁNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('351', 'TRUNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('435', 'TRUNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('471', 'TRUNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('581', 'TRUNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('741', 'TRUNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('376', 'TỐI', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('803', 'TỐI', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('204', 'ĐƠN SẮC', 'ĐƠN SẮC');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('227', 'ĐƠN SẮC', 'ĐƠN SẮC');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('413', 'SÁNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('771', 'SÁNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('360', 'TRUNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('436', 'TRUNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('473', 'TRUNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('585', 'TRUNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('861', 'TỐI', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('228', 'ĐƠN SẮC', 'ĐƠN SẮC');
-- bang_gia_chuan_melamine_plywood (12 rows)
INSERT INTO bang_gia_chuan_melamine_plywood (stt, do_day, gia_sang_trung, gia_toi, gia_don_sac_101, gia_don_sac_khac_da, gia_don_sac_106, loai_cot) VALUES (1, '5mm', 520000, 620000, 520000, 620000, 720000, 'EV');
INSERT INTO bang_gia_chuan_melamine_plywood (stt, do_day, gia_sang_trung, gia_toi, gia_don_sac_101, gia_don_sac_khac_da, gia_don_sac_106, loai_cot) VALUES (1, '5mm', 520000, 620000, 520000, 620000, 720000, 'SW Plywood keo Cp2');
INSERT INTO bang_gia_chuan_melamine_plywood (stt, do_day, gia_sang_trung, gia_toi, gia_don_sac_101, gia_don_sac_khac_da, gia_don_sac_106, loai_cot) VALUES (1, '5mm', 520000, 620000, 520000, 620000, 720000, 'E0');
INSERT INTO bang_gia_chuan_melamine_plywood (stt, do_day, gia_sang_trung, gia_toi, gia_don_sac_101, gia_don_sac_khac_da, gia_don_sac_106, loai_cot) VALUES (2, '9mm', 540000, 640000, 540000, 640000, 740000, 'EV');
INSERT INTO bang_gia_chuan_melamine_plywood (stt, do_day, gia_sang_trung, gia_toi, gia_don_sac_101, gia_don_sac_khac_da, gia_don_sac_106, loai_cot) VALUES (2, '9mm', 540000, 640000, 540000, 640000, 740000, 'SW Plywood keo Cp2');
INSERT INTO bang_gia_chuan_melamine_plywood (stt, do_day, gia_sang_trung, gia_toi, gia_don_sac_101, gia_don_sac_khac_da, gia_don_sac_106, loai_cot) VALUES (2, '9mm', 540000, 640000, 540000, 640000, 740000, 'E0');
INSERT INTO bang_gia_chuan_melamine_plywood (stt, do_day, gia_sang_trung, gia_toi, gia_don_sac_101, gia_don_sac_khac_da, gia_don_sac_106, loai_cot) VALUES (3, '18mm', 860000, 960000, 880000, 960000, 1060000, 'EV');
INSERT INTO bang_gia_chuan_melamine_plywood (stt, do_day, gia_sang_trung, gia_toi, gia_don_sac_101, gia_don_sac_khac_da, gia_don_sac_106, loai_cot) VALUES (3, '18mm', 860000, 960000, 880000, 960000, 1060000, 'SW Plywood keo Cp2');
INSERT INTO bang_gia_chuan_melamine_plywood (stt, do_day, gia_sang_trung, gia_toi, gia_don_sac_101, gia_don_sac_khac_da, gia_don_sac_106, loai_cot) VALUES (3, '18mm', 860000, 960000, 880000, 960000, 1060000, 'E0');
INSERT INTO bang_gia_chuan_melamine_plywood (stt, do_day, gia_sang_trung, gia_toi, gia_don_sac_101, gia_don_sac_khac_da, gia_don_sac_106, loai_cot) VALUES (4, '25mm', 1330000, 1430000, 1330000, 1430000, 1530000, 'EV');
INSERT INTO bang_gia_chuan_melamine_plywood (stt, do_day, gia_sang_trung, gia_toi, gia_don_sac_101, gia_don_sac_khac_da, gia_don_sac_106, loai_cot) VALUES (4, '25mm', 1330000, 1430000, 1330000, 1430000, 1530000, 'SW Plywood keo Cp2');
INSERT INTO bang_gia_chuan_melamine_plywood (stt, do_day, gia_sang_trung, gia_toi, gia_don_sac_101, gia_don_sac_khac_da, gia_don_sac_106, loai_cot) VALUES (4, '25mm', 1330000, 1430000, 1330000, 1430000, 1530000, 'E0');
-- bang_gia_chuan_melamine_nhua_osb_ghep (18 rows)
INSERT INTO bang_gia_chuan_melamine_nhua_osb_ghep (stt, loai_cot, do_day, gia_sang_trung, gia_toi_don_sac, gia_chum_104_106, giam_tru_sang_trung, giam_tru_toi_don_sac, giam_tru_chum_104_106) VALUES (1, 'DURABO 0.6', '5mm', 660000, 860000, 960000, NULL, NULL, NULL);
INSERT INTO bang_gia_chuan_melamine_nhua_osb_ghep (stt, loai_cot, do_day, gia_sang_trung, gia_toi_don_sac, gia_chum_104_106, giam_tru_sang_trung, giam_tru_toi_don_sac, giam_tru_chum_104_106) VALUES (2, 'DURABO 0.6', '8mm', 785000, 985000, 1085000, NULL, NULL, NULL);
INSERT INTO bang_gia_chuan_melamine_nhua_osb_ghep (stt, loai_cot, do_day, gia_sang_trung, gia_toi_don_sac, gia_chum_104_106, giam_tru_sang_trung, giam_tru_toi_don_sac, giam_tru_chum_104_106) VALUES (3, 'DURABO 0.6', '10mm', 880000, 1080000, 1180000, NULL, NULL, NULL);
INSERT INTO bang_gia_chuan_melamine_nhua_osb_ghep (stt, loai_cot, do_day, gia_sang_trung, gia_toi_don_sac, gia_chum_104_106, giam_tru_sang_trung, giam_tru_toi_don_sac, giam_tru_chum_104_106) VALUES (4, 'DURABO 0.6', '12mm', 970000, 1170000, 1270000, NULL, NULL, NULL);
INSERT INTO bang_gia_chuan_melamine_nhua_osb_ghep (stt, loai_cot, do_day, gia_sang_trung, gia_toi_don_sac, gia_chum_104_106, giam_tru_sang_trung, giam_tru_toi_don_sac, giam_tru_chum_104_106) VALUES (5, 'DURABO 0.6', '15mm', 1090000, 1290000, 1390000, NULL, NULL, NULL);
INSERT INTO bang_gia_chuan_melamine_nhua_osb_ghep (stt, loai_cot, do_day, gia_sang_trung, gia_toi_don_sac, gia_chum_104_106, giam_tru_sang_trung, giam_tru_toi_don_sac, giam_tru_chum_104_106) VALUES (6, 'DURABO 0.6', '17mm', 1175000, 1375000, 1475000, NULL, NULL, NULL);
INSERT INTO bang_gia_chuan_melamine_nhua_osb_ghep (stt, loai_cot, do_day, gia_sang_trung, gia_toi_don_sac, gia_chum_104_106, giam_tru_sang_trung, giam_tru_toi_don_sac, giam_tru_chum_104_106) VALUES (7, 'DURABO 0.5-0.55', '8mm', 760000, 960000, 1060000, NULL, NULL, NULL);
INSERT INTO bang_gia_chuan_melamine_nhua_osb_ghep (stt, loai_cot, do_day, gia_sang_trung, gia_toi_don_sac, gia_chum_104_106, giam_tru_sang_trung, giam_tru_toi_don_sac, giam_tru_chum_104_106) VALUES (8, 'DURABO 0.5-0.55', '9mm', 800000, 1000000, 1100000, NULL, NULL, NULL);
INSERT INTO bang_gia_chuan_melamine_nhua_osb_ghep (stt, loai_cot, do_day, gia_sang_trung, gia_toi_don_sac, gia_chum_104_106, giam_tru_sang_trung, giam_tru_toi_don_sac, giam_tru_chum_104_106) VALUES (9, 'DURABO 0.5-0.55', '15mm', 1040000, 1240000, 1340000, NULL, NULL, NULL);
INSERT INTO bang_gia_chuan_melamine_nhua_osb_ghep (stt, loai_cot, do_day, gia_sang_trung, gia_toi_don_sac, gia_chum_104_106, giam_tru_sang_trung, giam_tru_toi_don_sac, giam_tru_chum_104_106) VALUES (10, 'DURABO 0.5-0.55', '17mm', 1110000, 1310000, 1410000, NULL, NULL, NULL);
INSERT INTO bang_gia_chuan_melamine_nhua_osb_ghep (stt, loai_cot, do_day, gia_sang_trung, gia_toi_don_sac, gia_chum_104_106, giam_tru_sang_trung, giam_tru_toi_don_sac, giam_tru_chum_104_106) VALUES (11, 'Ván nhựa lõi đen 0.65', '8mm', 840000, 1040000, 1140000, NULL, NULL, NULL);
INSERT INTO bang_gia_chuan_melamine_nhua_osb_ghep (stt, loai_cot, do_day, gia_sang_trung, gia_toi_don_sac, gia_chum_104_106, giam_tru_sang_trung, giam_tru_toi_don_sac, giam_tru_chum_104_106) VALUES (12, 'Ván nhựa lõi đen 0.65', '17mm', 1130000, 1330000, 1430000, NULL, NULL, NULL);
INSERT INTO bang_gia_chuan_melamine_nhua_osb_ghep (stt, loai_cot, do_day, gia_sang_trung, gia_toi_don_sac, gia_chum_104_106, giam_tru_sang_trung, giam_tru_toi_don_sac, giam_tru_chum_104_106) VALUES (13, 'OSB Pine', '9mm', 750000, 950000, 1050000, NULL, NULL, NULL);
INSERT INTO bang_gia_chuan_melamine_nhua_osb_ghep (stt, loai_cot, do_day, gia_sang_trung, gia_toi_don_sac, gia_chum_104_106, giam_tru_sang_trung, giam_tru_toi_don_sac, giam_tru_chum_104_106) VALUES (14, 'OSB Pine', '12mm', 890000, 1090000, 1190000, NULL, NULL, NULL);
INSERT INTO bang_gia_chuan_melamine_nhua_osb_ghep (stt, loai_cot, do_day, gia_sang_trung, gia_toi_don_sac, gia_chum_104_106, giam_tru_sang_trung, giam_tru_toi_don_sac, giam_tru_chum_104_106) VALUES (15, 'OSB Pine', '18mm', 1010000, 1210000, 1310000, NULL, NULL, NULL);
INSERT INTO bang_gia_chuan_melamine_nhua_osb_ghep (stt, loai_cot, do_day, gia_sang_trung, gia_toi_don_sac, gia_chum_104_106, giam_tru_sang_trung, giam_tru_toi_don_sac, giam_tru_chum_104_106) VALUES (16, 'Gỗ ghép Cao su', '8mm', 990000, 1190000, 1290000, NULL, NULL, NULL);
INSERT INTO bang_gia_chuan_melamine_nhua_osb_ghep (stt, loai_cot, do_day, gia_sang_trung, gia_toi_don_sac, gia_chum_104_106, giam_tru_sang_trung, giam_tru_toi_don_sac, giam_tru_chum_104_106) VALUES (17, 'Gỗ ghép Cao su', '18mm', 1180000, 1380000, 1480000, NULL, NULL, NULL);
INSERT INTO bang_gia_chuan_melamine_nhua_osb_ghep (stt, loai_cot, do_day, gia_sang_trung, gia_toi_don_sac, gia_chum_104_106, giam_tru_sang_trung, giam_tru_toi_don_sac, giam_tru_chum_104_106) VALUES (99, 'Phủ 1 mặt giảm trừ', '', NULL, NULL, NULL, 220000, 320000, 370000);
-- bang_gia_chuan_veneer (4 rows)
INSERT INTO bang_gia_chuan_veneer (stt, loai, be_mat, gia_1m_a, gia_1m_b, gia_2m) VALUES (1, 'Tự nhiên', 'Xoan', 90000, 80000, 185000);
INSERT INTO bang_gia_chuan_veneer (stt, loai, be_mat, gia_1m_a, gia_1m_b, gia_2m) VALUES (2, 'Tự nhiên', 'Sồi', 150000, 140000, 320000);
INSERT INTO bang_gia_chuan_veneer (stt, loai, be_mat, gia_1m_a, gia_1m_b, gia_2m) VALUES (1, 'Kỹ thuật', 'Sồi kỹ thuật', 150000, NULL, 300000);
INSERT INTO bang_gia_chuan_veneer (stt, loai, be_mat, gia_1m_a, gia_1m_b, gia_2m) VALUES (2, 'Kỹ thuật', 'Walnut kỹ thuật', 170000, NULL, 340000);
-- bang_gia_chuan_mat_phu_khac (4 rows)
INSERT INTO bang_gia_chuan_mat_phu_khac (stt, ten, gia_1m, gia_2m, ghi_chu) VALUES (1, 'Keo trong (trên mặt veneer hoặc gỗ)', 40000, 80000, 'tối thiểu 20 tấm/ đơn');
INSERT INTO bang_gia_chuan_mat_phu_khac (stt, ten, gia_1m, gia_2m, ghi_chu) VALUES (2, 'Giấy PU/ Giấy vân gỗ', 25000, 50000, 'tối thiểu 20 tấm/ màu/ độ dày');
INSERT INTO bang_gia_chuan_mat_phu_khac (stt, ten, gia_1m, gia_2m, ghi_chu) VALUES (3, 'Bảo hộ trên melamine > 50 mặt', 20000, 40000, 'tối thiểu 10 tấm/loại');
INSERT INTO bang_gia_chuan_mat_phu_khac (stt, ten, gia_1m, gia_2m, ghi_chu) VALUES (4, 'Bảo hộ trên melamine < 50 mặt', 40000, 80000, 'tối thiểu 10 tấm/loại');
-- bang_gia_chuan_chi_nep (9 rows)
INSERT INTO bang_gia_chuan_chi_nep (stt, nhom, cuon, gia_a, gia_b, gia_c, gia_d) VALUES (1, 'PVC', '101, 100, 104 (T/SH)', 140000, 340000, 200000, NULL);
INSERT INTO bang_gia_chuan_chi_nep (stt, nhom, cuon, gia_a, gia_b, gia_c, gia_d) VALUES (2, 'PVC', 'Chỉ PVC vân gỗ, Đơn sắc còn lại', 170000, 370000, 260000, NULL);
INSERT INTO bang_gia_chuan_chi_nep (stt, nhom, cuon, gia_a, gia_b, gia_c, gia_d) VALUES (1, 'VENEER', 'Xoan', 145000, 290000, 85000, 170000);
INSERT INTO bang_gia_chuan_chi_nep (stt, nhom, cuon, gia_a, gia_b, gia_c, gia_d) VALUES (2, 'VENEER', 'Sồi', 155000, 310000, 90000, 180000);
INSERT INTO bang_gia_chuan_chi_nep (stt, nhom, cuon, gia_a, gia_b, gia_c, gia_d) VALUES (3, 'VENEER', 'Walnut kỹ thuật', 250000, 500000, 180000, 360000);
INSERT INTO bang_gia_chuan_chi_nep (stt, nhom, cuon, gia_a, gia_b, gia_c, gia_d) VALUES (1, 'ACRYLIC', 'Chỉ Acrylic mã AS và AM', 450000, 414000, NULL, NULL);
INSERT INTO bang_gia_chuan_chi_nep (stt, nhom, cuon, gia_a, gia_b, gia_c, gia_d) VALUES (1, 'ABS_PVC', 'Chỉ ABS màu SS18-28-38-903', 360000, NULL, NULL, NULL);
INSERT INTO bang_gia_chuan_chi_nep (stt, nhom, cuon, gia_a, gia_b, gia_c, gia_d) VALUES (2, 'ABS_PVC', 'Chỉ DOLLKEN US 101-102-103-104-105-106, Chỉ DOLLKEN UM 107', NULL, 500000, NULL, NULL);
INSERT INTO bang_gia_chuan_chi_nep (stt, nhom, cuon, gia_a, gia_b, gia_c, gia_d) VALUES (3, 'ABS_PVC', 'Chỉ PVC SB 001-009', NULL, 100000, NULL, NULL);
-- bang_gia_chuan_keo_hat (9 rows)
INSERT INTO bang_gia_chuan_keo_hat (stt, ma, nhiet_do, mau, gia_1kg, gia_25kg) VALUES (1, 'BOSTIK 9338', '145-165', 'Kem', 80000, 2000000);
INSERT INTO bang_gia_chuan_keo_hat (stt, ma, nhiet_do, mau, gia_1kg, gia_25kg) VALUES (2, 'BOSTIK 7523', '160-180', 'Trắng sữa', 70000, 1750000);
INSERT INTO bang_gia_chuan_keo_hat (stt, ma, nhiet_do, mau, gia_1kg, gia_25kg) VALUES (3, 'BOSTIK 7680', '175-195', 'Trắng', 70000, 1750000);
INSERT INTO bang_gia_chuan_keo_hat (stt, ma, nhiet_do, mau, gia_1kg, gia_25kg) VALUES (4, 'BOSTIK 7681', '175-195', 'Be', 70000, 2000000);
INSERT INTO bang_gia_chuan_keo_hat (stt, ma, nhiet_do, mau, gia_1kg, gia_25kg) VALUES (5, 'JOWAT 282.15', '145-165', 'Kem', 80000, 2000000);
INSERT INTO bang_gia_chuan_keo_hat (stt, ma, nhiet_do, mau, gia_1kg, gia_25kg) VALUES (6, 'JOWAT 288.60', '180-200', 'Kem', 90000, 2250000);
INSERT INTO bang_gia_chuan_keo_hat (stt, ma, nhiet_do, mau, gia_1kg, gia_25kg) VALUES (7, 'JOWAT 288.61', '180-200', 'Trắng', 90000, 2250000);
INSERT INTO bang_gia_chuan_keo_hat (stt, ma, nhiet_do, mau, gia_1kg, gia_25kg) VALUES (8, 'JOWAT 296.80', '190-200', 'Kem', 80000, 2000000);
INSERT INTO bang_gia_chuan_keo_hat (stt, ma, nhiet_do, mau, gia_1kg, gia_25kg) VALUES (9, 'JOWAT 280.58', '180-210', 'Trong', 123000, 3075000);
-- bang_gia_chuan_98_mau (12 rows)
INSERT INTO bang_gia_chuan_98_mau (stt, wood_1, wood_2, wood_3, wood_4, wood_5, wood_6, wood_7, art, color_code, color_name) VALUES (1, '029', '330', '389', '425', '444', '503', '725', 'D5', 430, 'White Dove 109');
INSERT INTO bang_gia_chuan_98_mau (stt, wood_1, wood_2, wood_3, wood_4, wood_5, wood_6, wood_7, art, color_code, color_name) VALUES (2, '0439', '331', '402', '426', '445', '530', '737', 'D8', 431, 'Basic White 108');
INSERT INTO bang_gia_chuan_98_mau (stt, wood_1, wood_2, wood_3, wood_4, wood_5, wood_6, wood_7, art, color_code, color_name) VALUES (3, '161', '332', '403', '427', '447', '577', '740', 901, NULL, 'Tortilla 203');
INSERT INTO bang_gia_chuan_98_mau (stt, wood_1, wood_2, wood_3, wood_4, wood_5, wood_6, wood_7, art, color_code, color_name) VALUES (4, '184', '333', '404', '428', '448', '601', '741', NULL, NULL, 'Flamingo Pink 021');
INSERT INTO bang_gia_chuan_98_mau (stt, wood_1, wood_2, wood_3, wood_4, wood_5, wood_6, wood_7, art, color_code, color_name) VALUES (5, '201', '335', '405', '429', '460', '609', '750', NULL, NULL, 'Sky Blue 050');
INSERT INTO bang_gia_chuan_98_mau (stt, wood_1, wood_2, wood_3, wood_4, wood_5, wood_6, wood_7, art, color_code, color_name) VALUES (6, '209', '337', '407', '432', '467', '611', '786', NULL, NULL, 'Frosted Blue 052');
INSERT INTO bang_gia_chuan_98_mau (stt, wood_1, wood_2, wood_3, wood_4, wood_5, wood_6, wood_7, art, color_code, color_name) VALUES (7, '212', '338', '412', '434', '469', '612', '803', NULL, NULL, 'Greenery 073');
INSERT INTO bang_gia_chuan_98_mau (stt, wood_1, wood_2, wood_3, wood_4, wood_5, wood_6, wood_7, art, color_code, color_name) VALUES (8, '217', '340', '413', '435', '471', '613', '771', NULL, NULL, 'Simply White 101');
INSERT INTO bang_gia_chuan_98_mau (stt, wood_1, wood_2, wood_3, wood_4, wood_5, wood_6, wood_7, art, color_code, color_name) VALUES (9, '240', '376', '414', '436', '473', '614', '809', NULL, NULL, 'Jet Black 230');
INSERT INTO bang_gia_chuan_98_mau (stt, wood_1, wood_2, wood_3, wood_4, wood_5, wood_6, wood_7, art, color_code, color_name) VALUES (10, '303', '385', '421', '440', '474', '622', '861', NULL, NULL, 'Iron Grey 204');
INSERT INTO bang_gia_chuan_98_mau (stt, wood_1, wood_2, wood_3, wood_4, wood_5, wood_6, wood_7, art, color_code, color_name) VALUES (11, '320', '386', '423', '442', '501', '642', '862', NULL, NULL, NULL);
INSERT INTO bang_gia_chuan_98_mau (stt, wood_1, wood_2, wood_3, wood_4, wood_5, wood_6, wood_7, art, color_code, color_name) VALUES (12, '325', '388', '424', '443', '502', '668', NULL, NULL, NULL, NULL);