-- bang_gia_chuan_mau_melamine_2 (216 rows)
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('184', 'SÁNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('421', 'SÁNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('D3', 'SÁNG', 'ĐÁ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('0029', 'TRUNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('380', 'TRUNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('439', 'TRUNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('474', 'TRUNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('609', 'TRUNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('742', 'TRUNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('D1', 'TRUNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('711', 'TRUNG', 'ART');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('D2', 'TRUNG', 'ĐÁ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('0446', 'TRUNG', 'VẢI');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('132', 'TỐI', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('414', 'TỐI', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('D4', 'TỐI', 'ĐÁ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('702', 'TỐI', 'VẢI');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('021', 'ĐƠN SẮC', 'ĐƠN SẮC');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('200', 'ĐƠN SẮC', 'ĐƠN SẮC');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('217', 'SÁNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('424', 'SÁNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('D5', 'SÁNG', 'ĐÁ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('142', 'TRUNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('385', 'TRUNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('440', 'TRUNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('484', 'TRUNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('612', 'TRUNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('750', 'TRUNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('4028', 'TRUNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('713', 'TRUNG', 'ART');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('D7', 'TRUNG', 'ĐÁ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('701', 'TRUNG', 'VẢI');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('136', 'TỐI', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('423', 'TỐI', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('D8', 'TỐI', 'ĐÁ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('041', 'ĐƠN SẮC', 'ĐƠN SẮC');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('025', 'ĐƠN SẮC', 'ĐƠN SẮC');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('240', 'SÁNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('429', 'SÁNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('D6', 'SÁNG', 'ĐÁ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('145', 'TRUNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('386', 'TRUNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('443', 'TRUNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('485', 'TRUNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('642', 'TRUNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('757', 'TRUNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('4029', 'TRUNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('901', 'TRUNG', 'ĐÁ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('703', 'TRUNG', 'VẢI');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('139', 'TỐI', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('442', 'TỐI', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('030', 'ĐƠN SẮC', 'ĐƠN SẮC');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('0212', 'ĐƠN SẮC', 'ĐƠN SẮC');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('301', 'SÁNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('452', 'SÁNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('D9', 'SÁNG', 'ĐÁ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('201', 'TRUNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('387', 'TRUNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('444', 'TRUNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('502', 'TRUNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('668', 'TRUNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('776', 'TRUNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('4030', 'TRUNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('D10', 'TRUNG', 'ĐÁ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('704', 'TRUNG', 'VẢI');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('161', 'TỐI', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('530', 'TỐI', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('220', 'ĐƠN SẮC', 'ĐƠN SẮC');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('213', 'ĐƠN SẮC', 'ĐƠN SẮC');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('311', 'SÁNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('468', 'SÁNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('D11', 'SÁNG', 'ĐÁ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('209', 'TRUNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('404', 'TRUNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('445', 'TRUNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('503', 'TRUNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('682', 'TRUNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('783', 'TRUNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('4457', 'TRUNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('430', 'TRUNG', 'ĐÁ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('998', 'TRUNG', 'VẢI');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('268', 'TỐI', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('556', 'TỐI', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('073', 'ĐƠN SẮC', 'ĐƠN SẮC');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('215', 'ĐƠN SẮC', 'ĐƠN SẮC');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('319', 'SÁNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('501', 'SÁNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('212', 'TRUNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('405', 'TRUNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('446', 'TRUNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('521', 'TRUNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('683', 'TRUNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('786', 'TRUNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('0439', 'TRUNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('431', 'TRUNG', 'ĐÁ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('303', 'TỐI', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('590', 'TỐI', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('051', 'ĐƠN SẮC', 'ĐƠN SẮC');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('216', 'ĐƠN SẮC', 'ĐƠN SẮC');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('320', 'SÁNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('504', 'SÁNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('23015', 'TRUNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('407', 'TRUNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('447', 'TRUNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('524', 'TRUNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('684', 'TRUNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('787', 'TRUNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('0330', 'TRUNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('458', 'TRUNG', 'ĐÁ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('312', 'TỐI', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('601', 'TỐI', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('050', 'ĐƠN SẮC', 'ĐƠN SẮC');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('219', 'ĐƠN SẮC', 'ĐƠN SẮC');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('321', 'SÁNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('610', 'SÁNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('330', 'TRUNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('416', 'TRUNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('448', 'TRUNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('533', 'TRUNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('686', 'TRUNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('789', 'TRUNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('984', 'TRUNG', 'ĐÁ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('302', 'TỐI', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('613', 'TỐI', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('052', 'ĐƠN SẮC', 'ĐƠN SẮC');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('104', 'ĐƠN SẮC', 'ĐƠN SẮC');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('325', 'SÁNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('611', 'SÁNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('331', 'TRUNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('425', 'TRUNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('460', 'TRUNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('541', 'TRUNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('689', 'TRUNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('809', 'TRUNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('322', 'TỐI', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('614', 'TỐI', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('026', 'ĐƠN SẮC', 'ĐƠN SẮC');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('106', 'ĐƠN SẮC', 'ĐƠN SẮC');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('388', 'SÁNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('621', 'SÁNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('332', 'TRUNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('426', 'TRUNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('463', 'TRUNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('545', 'TRUNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('714', 'TRUNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('810', 'TRUNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('329', 'TỐI', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('719', 'TỐI', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('089', 'ĐƠN SẮC', 'ĐƠN SẮC');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('033', 'ĐƠN SẮC', 'ĐƠN SẮC');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('389', 'SÁNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('622', 'SÁNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('335', 'TRUNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('427', 'TRUNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('464', 'TRUNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('551', 'TRUNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('722', 'TRUNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('862', 'TRUNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('333', 'TỐI', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('725', 'TỐI', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('027', 'ĐƠN SẮC', 'ĐƠN SẮC');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('034', 'ĐƠN SẮC', 'ĐƠN SẮC');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('402', 'SÁNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('681', 'SÁNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('337', 'TRUNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('428', 'TRUNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('467', 'TRUNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('571', 'TRUNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('728', 'TRUNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('902', 'TRUNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('336', 'TỐI', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('735', 'TỐI', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('203', 'ĐƠN SẮC', 'ĐƠN SẮC');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('222', 'ĐƠN SẮC', 'ĐƠN SẮC');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('403', 'SÁNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('708', 'SÁNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('340', 'TRUNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('432', 'TRUNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('469', 'TRUNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('572', 'TRUNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('736', 'TRUNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('960', 'TRUNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('338', 'TỐI', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('743', 'TỐI', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('100', 'ĐƠN SẮC', 'ĐƠN SẮC');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('224', 'ĐƠN SẮC', 'ĐƠN SẮC');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('410', 'SÁNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('740', 'SÁNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('350', 'TRUNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('434', 'TRUNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('470', 'TRUNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('577', 'TRUNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('737', 'TRUNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('370', 'TỐI', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('744', 'TỐI', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('230', 'ĐƠN SẮC', 'ĐƠN SẮC');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('226', 'ĐƠN SẮC', 'ĐƠN SẮC');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('412', 'SÁNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('759', 'SÁNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('351', 'TRUNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('435', 'TRUNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('471', 'TRUNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('581', 'TRUNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('741', 'TRUNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('376', 'TỐI', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('803', 'TỐI', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('204', 'ĐƠN SẮC', 'ĐƠN SẮC');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('227', 'ĐƠN SẮC', 'ĐƠN SẮC');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('413', 'SÁNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('771', 'SÁNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('360', 'TRUNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('436', 'TRUNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('473', 'TRUNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('585', 'TRUNG', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('861', 'TỐI', 'VÂN GỖ');
INSERT INTO bang_gia_chuan_mau_melamine_2 (ma_mau, nhom, phan_nhom) VALUES ('228', 'ĐƠN SẮC', 'ĐƠN SẮC');
-- bang_gia_chuan_melamine_plywood (3 rows)
INSERT INTO bang_gia_chuan_melamine_plywood (stt, loai_cot, do_day, gia_sang_trung, gia_toi, gia_don_sac_101, gia_don_sac_khac_da, gia_don_sac_106) VALUES (2, '', '9mm', 540000, 640000, 540000, 640000, 740000);
INSERT INTO bang_gia_chuan_melamine_plywood (stt, loai_cot, do_day, gia_sang_trung, gia_toi, gia_don_sac_101, gia_don_sac_khac_da, gia_don_sac_106) VALUES (3, '', '18mm', 860000, 960000, 880000, 960000, 1060000);
INSERT INTO bang_gia_chuan_melamine_plywood (stt, loai_cot, do_day, gia_sang_trung, gia_toi, gia_don_sac_101, gia_don_sac_khac_da, gia_don_sac_106) VALUES (4, '', '25mm', 1330000, 1430000, 1330000, 1430000, 1530000);
-- bang_gia_chuan_melamine_nhua_osb_ghep (18 rows)
INSERT INTO bang_gia_chuan_melamine_nhua_osb_ghep (stt, loai_cot, do_day, gia_sang_trung, gia_toi_don_sac, gia_chum_104_106) VALUES (1, 'DURABO 0.6', '5mm', 660000, 860000, 960000);
INSERT INTO bang_gia_chuan_melamine_nhua_osb_ghep (stt, loai_cot, do_day, gia_sang_trung, gia_toi_don_sac, gia_chum_104_106) VALUES (2, 'DURABO 0.6', '8mm', 785000, 985000, 1085000);
INSERT INTO bang_gia_chuan_melamine_nhua_osb_ghep (stt, loai_cot, do_day, gia_sang_trung, gia_toi_don_sac, gia_chum_104_106) VALUES (3, 'DURABO 0.6', '10mm', 880000, 1080000, 1180000);
INSERT INTO bang_gia_chuan_melamine_nhua_osb_ghep (stt, loai_cot, do_day, gia_sang_trung, gia_toi_don_sac, gia_chum_104_106) VALUES (4, 'DURABO 0.6', '12mm', 970000, 1170000, 1270000);
INSERT INTO bang_gia_chuan_melamine_nhua_osb_ghep (stt, loai_cot, do_day, gia_sang_trung, gia_toi_don_sac, gia_chum_104_106) VALUES (5, 'DURABO 0.6', '15mm', 1090000, 1290000, 1390000);
INSERT INTO bang_gia_chuan_melamine_nhua_osb_ghep (stt, loai_cot, do_day, gia_sang_trung, gia_toi_don_sac, gia_chum_104_106) VALUES (6, 'DURABO 0.6', '17mm', 1175000, 1375000, 1475000);
INSERT INTO bang_gia_chuan_melamine_nhua_osb_ghep (stt, loai_cot, do_day, gia_sang_trung, gia_toi_don_sac, gia_chum_104_106) VALUES (7, 'DURABO 0.5-0.55', '8mm', 760000, 960000, 1060000);
INSERT INTO bang_gia_chuan_melamine_nhua_osb_ghep (stt, loai_cot, do_day, gia_sang_trung, gia_toi_don_sac, gia_chum_104_106) VALUES (8, 'DURABO 0.5-0.55', '9mm', 800000, 1000000, 1100000);
INSERT INTO bang_gia_chuan_melamine_nhua_osb_ghep (stt, loai_cot, do_day, gia_sang_trung, gia_toi_don_sac, gia_chum_104_106) VALUES (9, 'DURABO 0.5-0.55', '15mm', 1040000, 1240000, 1340000);
INSERT INTO bang_gia_chuan_melamine_nhua_osb_ghep (stt, loai_cot, do_day, gia_sang_trung, gia_toi_don_sac, gia_chum_104_106) VALUES (10, 'DURABO 0.5-0.55', '17mm', 1110000, 1310000, 1410000);
INSERT INTO bang_gia_chuan_melamine_nhua_osb_ghep (stt, loai_cot, do_day, gia_sang_trung, gia_toi_don_sac, gia_chum_104_106) VALUES (11, 'Ván nhựa lõi đen 0.65', '8mm', 840000, 1040000, 1140000);
INSERT INTO bang_gia_chuan_melamine_nhua_osb_ghep (stt, loai_cot, do_day, gia_sang_trung, gia_toi_don_sac, gia_chum_104_106) VALUES (12, 'Ván nhựa lõi đen 0.65', '17mm', 1130000, 1330000, 1430000);
INSERT INTO bang_gia_chuan_melamine_nhua_osb_ghep (stt, loai_cot, do_day, gia_sang_trung, gia_toi_don_sac, gia_chum_104_106) VALUES (13, 'OSB Pine', '9mm', 750000, 950000, 1050000);
INSERT INTO bang_gia_chuan_melamine_nhua_osb_ghep (stt, loai_cot, do_day, gia_sang_trung, gia_toi_don_sac, gia_chum_104_106) VALUES (14, 'OSB Pine', '12mm', 890000, 1090000, 1190000);
INSERT INTO bang_gia_chuan_melamine_nhua_osb_ghep (stt, loai_cot, do_day, gia_sang_trung, gia_toi_don_sac, gia_chum_104_106) VALUES (15, 'OSB Pine', '18mm', 1010000, 1210000, 1310000);
INSERT INTO bang_gia_chuan_melamine_nhua_osb_ghep (stt, loai_cot, do_day, gia_sang_trung, gia_toi_don_sac, gia_chum_104_106) VALUES (16, 'Gỗ ghép Cao su', '8mm', 990000, 1190000, 1290000);
INSERT INTO bang_gia_chuan_melamine_nhua_osb_ghep (stt, loai_cot, do_day, gia_sang_trung, gia_toi_don_sac, gia_chum_104_106) VALUES (17, 'Gỗ ghép Cao su', '18mm', 1180000, 1380000, 1480000);
INSERT INTO bang_gia_chuan_melamine_nhua_osb_ghep (stt, loai_cot, do_day, gia_sang_trung, gia_toi_don_sac, gia_chum_104_106) VALUES (99, 'Phủ 1 mặt giảm trừ', '', NULL, NULL, NULL);