// Generated by Wrangler by running `wrangler types`

interface Env {
	APP_VERSION: "0.2.4";
	APP_INSTALLER_URL: "https://github.com/tranphongh2t-ship-it/gia-ban-releases/releases/latest/download/THANH.THUY.PRICE.Setup.0.2.4.exe";
	APP_UPDATE_NOTES: "Bản 0.2.4: người có quyền Import được xóa hết dữ liệu Check giá gốc - CK và Sổ chi tiết bán hàng.";
	DB: D1Database;
}
