export interface ComputeActions {
  tinhToan?: string
  autoAssign?: string
  autoGenerate?: string
}

export interface SheetConfig {
  slug: string
  label: string
  apiPath: string
  columns: { key: string; label: string; type?: 'number'; readOnly?: boolean }[]
  compute?: ComputeActions
}

export const sheetConfigs: SheetConfig[] = [
  {
    slug: 'van-dam-okal',
    label: 'VÁN DĂM OKAL',
    apiPath: 'van-dam-okal',
    columns: [
      { key: 'stt', label: 'STT' },
      { key: 'quy_cach', label: 'Quy cách 1220x2440 (mm)' },
      { key: 'e2', label: 'E2', type: 'number' },
      { key: 'veco_e1', label: 'VECO E1', type: 'number' },
      { key: 'veco_cp2', label: 'VECO CP2', type: 'number' },
      { key: 'veco_f4s', label: 'VECO F4S', type: 'number' },
      { key: 'hmr_e1', label: 'HMR E1', type: 'number' },
    ],
    compute: { tinhToan: 'tinh-gia-vdo/tinh-toan', autoAssign: 'tinh-gia-vdo/auto-assign-ma-sp' },
  },
  {
    slug: 'van-mdf-hdf',
    label: 'VÁN MDF HDF',
    apiPath: 'van-mdf-hdf',
    columns: [
      { key: 'stt', label: 'STT' },
      { key: 'quy_cach', label: 'Quy cách 1220x2440 (mm)' },
      // Việt Nam nhóm 1
      { key: 'vn_ldf_e2', label: 'VN-LDF E2', type: 'number' },
      { key: 'vn_mdf_e2', label: 'VN-MDF E2', type: 'number' },
      { key: 'vn_mdf_cp2', label: 'VN-MDF CP2', type: 'number' },
      { key: 'vn_hdf_hmr_e2', label: 'VN-HDF HMR E2', type: 'number' },
      { key: 'vn_hdf_hmr_e1', label: 'VN-HDF HMR E1', type: 'number' },
      // Thái Lan nhóm 1
      { key: 'th_mdf_e2', label: 'TL-MDF E2', type: 'number' },
      { key: 'th_hdf_hmr_e2', label: 'TL-HDF HMR E2', type: 'number' },
      // Việt Nam nhóm 2
      { key: 'vn_lmr_e2', label: 'VN-LMR E2', type: 'number' },
      { key: 'vn_mmr_e2', label: 'VN-MMR E2', type: 'number' },
      // HMR (Việt Nam)
      { key: 'vn_hmr_e2', label: 'HMR E2', type: 'number' },
      { key: 'vn_hmr_e1', label: 'HMR E1', type: 'number' },
      { key: 'vn_hmr_cp2', label: 'HMR CP2', type: 'number' },
      // Thái Lan nhóm 2
      { key: 'th_mmr_e2', label: 'TL-MMR E2', type: 'number' },
      { key: 'th_hmr_v313_e1', label: 'TL-HMR V313 E1', type: 'number' },
    ],
    compute: { tinhToan: 'tinh-gia-vmh/tinh-toan', autoAssign: 'tinh-gia-vmh/auto-assign-ma-sp' },
  },
  {
    slug: 'phu-thu-melamine',
    label: 'Phụ thu Melamine',
    apiPath: 'phu-thu-melamine',
    columns: [
      { key: 'stt', label: 'STT' },
      { key: 'mo_ta', label: 'Mô tả' },
      { key: 'basic_1m', label: 'Basic 1 mặt', type: 'number' },
      { key: 'basic_2m', label: 'Basic 2 mặt', type: 'number' },
      { key: 'eco_1m', label: 'Eco 1 mặt', type: 'number' },
      { key: 'eco_2m', label: 'Eco 2 mặt', type: 'number' },
      { key: 'standard_1m', label: 'Standard 1 mặt', type: 'number' },
      { key: 'standard_2m', label: 'Standard 2 mặt', type: 'number' },
      { key: 'premium_wood_art_1m', label: 'Premium W/A 1 mặt', type: 'number' },
      { key: 'premium_wood_art_2m', label: 'Premium W/A 2 mặt', type: 'number' },
      { key: 'premium_color_1m', label: 'Premium Màu 1 mặt', type: 'number' },
      { key: 'premium_color_2m', label: 'Premium Màu 2 mặt', type: 'number' },
      { key: 'superb_1m', label: 'Superb 1 mặt', type: 'number' },
      { key: 'superb_2m', label: 'Superb 2 mặt', type: 'number' },
    ],
  },
  {
    slug: 'mau-melamine',
    label: 'Nhóm màu Melamine 220',
    apiPath: 'mau-melamine',
    columns: [
      { key: 'stt', label: 'STT' },
      { key: 'nhom', label: 'Nhóm' },
      { key: 'loai', label: 'Loại' },
      { key: 'ma_mau', label: 'Mã màu' },
      { key: 'vi_tri', label: 'Vị trí' },
    ],
  },
  {
    slug: 'van-ep',
    label: 'Ván Ép Thanh Thùy',
    apiPath: 'van-ep',
    columns: [
      { key: 'stt', label: 'STT' },
      { key: 'quy_cach', label: 'Độ dày' },
      { key: 'kt_1000x2000', label: 'Ash/mỡ CD 1000x2000', type: 'number' },
      { key: 'kt_1220x2440', label: 'Ash/mỡ CD 1220x2440', type: 'number' },
    ],
    compute: { tinhToan: 'tinh-gia-ve/tinh-toan', autoAssign: 'tinh-gia-ve/auto-assign-ma-sp' },
  },
  {
    slug: 'van-ep-khac',
    label: 'Ván Ép Khác',
    apiPath: 'van-ep-khac',
    columns: [
      { key: 'stt', label: 'STT' },
      { key: 'quy_cach', label: 'Độ dày' },
      { key: 'loai', label: 'Loại' },
      { key: 'gia', label: 'Giá', type: 'number' },
      { key: 'nhom', label: 'Nhóm' },
    ],
    compute: { tinhToan: 'tinh-gia-ve/tinh-toan', autoAssign: 'tinh-gia-ve/auto-assign-ma-sp' },
  },
  {
    slug: 'pvc-film-dura',
    label: 'PVC FILM - DURA+',
    apiPath: 'pvc-film-dura',
    columns: [
      { key: 'stt', label: 'STT' },
      { key: 'ma_mau', label: 'Mã màu' },
      { key: 'nhom', label: 'Nhóm' },
      { key: 'loai', label: 'Loại' },
      { key: 'thong_so', label: 'Thông số' },
    ],
    compute: { tinhToan: 'tinh-gia-pvc-petg/tinh-toan', autoAssign: 'tinh-gia-pvc-petg/auto-assign-ma-sp' },
  },
  {
    slug: 'van-phu-pvc-petg',
    label: 'VÁN PHỦ PVC FILM - PETG',
    apiPath: 'van-phu-pvc-petg',
    columns: [
      { key: 'stt', label: 'STT' },
      { key: 'loai_van', label: 'Loại ván' },
      { key: 'do_day', label: 'Độ dày' },
      { key: 'gia_uu_dai_1m', label: 'Ưu đãi 1m', type: 'number' },
      { key: 'gia_uu_dai_2m', label: 'Ưu đãi 2m', type: 'number' },
      { key: 'gia_standard_1m', label: 'Standard 1m', type: 'number' },
      { key: 'gia_standard_2m', label: 'Standard 2m', type: 'number' },
      { key: 'gia_premium_1m', label: 'Premium 1m', type: 'number' },
      { key: 'gia_premium_2m', label: 'Premium 2m', type: 'number' },
      { key: 'gia_petg_1m', label: 'PETG 1m', type: 'number' },
      { key: 'gia_petg_2m', label: 'PETG 2m', type: 'number' },
    ],
    compute: { tinhToan: 'tinh-gia-pvc-petg/tinh-toan', autoAssign: 'tinh-gia-pvc-petg/auto-assign-ma-sp' },
  },
  {
    slug: 'durabo',
    label: 'Ván nhựa DURABO',
    apiPath: 'durabo',
    columns: [
      { key: 'stt', label: 'STT' },
      { key: 'quy_cach', label: 'Quy cách' },
      { key: 'loai', label: 'Loại' },
      { key: 'nhom', label: 'Nhóm' },
      { key: 'gia', label: 'Giá', type: 'number' },
      { key: 'dong_goi', label: 'Đóng gói' },
    ],
    compute: { tinhToan: 'tinh-gia-dr/tinh-toan' },
  },
  {
    slug: 'osb',
    label: 'OSB',
    apiPath: 'osb',
    columns: [
      { key: 'stt', label: 'STT' },
      { key: 'mo_ta', label: 'Mô tả' },
      { key: 'do_day', label: 'Độ dày' },
      { key: 'gia', label: 'Giá gốc', type: 'number' },
      { key: 'gia_da_ck_10', label: 'Đã CK 10%', type: 'number' },
      { key: 'gia_da_ck_15', label: 'Đã CK 15%', type: 'number' },
      { key: 'gia_chua_ck_10', label: 'Chưa CK 10%', type: 'number' },
      { key: 'gia_chua_ck_15', label: 'Chưa CK 15%', type: 'number' },
      { key: 'tam_kien', label: 'Tấm/kiện', type: 'number' },
    ],
    compute: { tinhToan: 'tinh-gia-osb/tinh-toan' },
  },
  {
    slug: 'go-ghep',
    label: 'Gỗ Trơn (Gỗ Ghép)',
    apiPath: 'go-ghep',
    columns: [
      { key: 'stt', label: 'STT' },
      { key: 'quy_cach', label: 'Quy cách 1200x2400 (mm)' },
      { key: 'cao_su_aa_ab', label: 'Cao Su AA/AB', type: 'number' },
      { key: 'cao_su_ac', label: 'Cao Su AC', type: 'number' },
      { key: 'cao_su_bc', label: 'Cao Su BC', type: 'number' },
      { key: 'cao_su_cc', label: 'Cao Su CC', type: 'number' },
      { key: 'thong_nzl_aa', label: 'Thông NZL AA', type: 'number' },
    ],
    compute: { tinhToan: 'tinh-gia-gg/tinh-toan', autoAssign: 'tinh-gia-gg/auto-assign-ma-sp' },
  },
  {
    slug: 'phu-veneer',
    label: 'Phủ Veneer (Gỗ Ghép)',
    apiPath: 'phu-veneer',
    columns: [
      { key: 'stt', label: 'STT' },
      { key: 'quy_cach', label: 'Quy cách 1220x2440 (mm)' },
      { key: 'xoan_1m', label: 'Xoan 1 mặt', type: 'number' },
      { key: 'xoan_2m', label: 'Xoan 2 mặt', type: 'number' },
      { key: 'soi_1m', label: 'Sồi 1 mặt', type: 'number' },
      { key: 'soi_2m', label: 'Sồi 2 mặt', type: 'number' },
      { key: 'soi_kt_1m', label: 'Sồi KT 1 mặt', type: 'number' },
      { key: 'soi_kt_2m', label: 'Sồi KT 2 mặt', type: 'number' },
      { key: 'oc_cho_kt_1m', label: 'Óc Chó KT 1 mặt', type: 'number' },
      { key: 'oc_cho_kt_2m', label: 'Óc Chó KT 2 mặt', type: 'number' },
    ],
    compute: { tinhToan: 'tinh-gia-gg/tinh-toan', autoAssign: 'tinh-gia-gg/auto-assign-ma-sp' },
  },
  {
    slug: 'veneer',
    label: 'VENEER',
    apiPath: 'veneer',
    columns: [
      { key: 'stt', label: 'STT' },
      { key: 'loai', label: 'Loại' },
      { key: 'be_mat', label: 'Bề mặt' },
      { key: 'gia_1m_a', label: 'Giá 1 mặt A', type: 'number' },
      { key: 'gia_1m_b', label: 'Giá 1 mặt B', type: 'number' },
      { key: 'gia_2m', label: 'Giá 2 mặt AB/AA', type: 'number' },
    ],
    compute: { autoAssign: 'veneer/auto-assign-ma-sp' },
  },
  {
    slug: 'mat-phu-khac',
    label: 'Mặt phủ khác',
    apiPath: 'mat-phu-khac',
    columns: [
      { key: 'stt', label: 'STT' },
      { key: 'ten', label: 'Tên' },
      { key: 'gia_1m', label: 'Giá 1 mặt', type: 'number' },
      { key: 'gia_2m', label: 'Giá 2 mặt', type: 'number' },
      { key: 'ghi_chu', label: 'Ghi chú' },
    ],
  },
  {
    slug: 'acrylic',
    label: 'Acrylic Mã màu',
    apiPath: 'acrylic',
    columns: [
      { key: 'stt', label: 'STT' },
      { key: 'series', label: 'Series' },
      { key: 'ma_mau', label: 'Mã màu' },
      { key: 'loai_mau', label: 'Loại màu' },
      { key: 'gia', label: 'Giá/tờ', type: 'number' },
    ],
    compute: { tinhToan: 'tinh-gia-acrylic/tinh-toan' },
  },
  {
    slug: 'van-phu-acrylic',
    label: 'Ván phủ Acrylic',
    apiPath: 'van-phu-acrylic',
    columns: [
      { key: 'stt', label: 'STT' },
      { key: 'series', label: 'Series' },
      { key: 'phu', label: 'Phủ' },
      { key: 'board_type', label: 'Loại ván' },
      { key: 'gia_ds', label: 'Giá Đơn sắc', type: 'number' },
      { key: 'gia_ak', label: 'Giá Ánh kim', type: 'number' },
      { key: 'gia_vg', label: 'Giá Vân gỗ', type: 'number' },
    ],
    compute: { tinhToan: 'tinh-gia-acrylic/tinh-toan' },
  },
  {
    slug: 'one-laminate',
    label: 'One Laminate Mã màu',
    apiPath: 'one-laminate',
    columns: [
      { key: 'stt', label: 'STT' },
      { key: 'nhom', label: 'Nhóm' },
      { key: 'ma_mau', label: 'Mã màu' },
      { key: 'gia_foil', label: 'Giá foil', type: 'number' },
    ],
  },
  {
    slug: 'van-nhua-phu-hpl',
    label: 'Ván nhựa phủ HPL',
    apiPath: 'van-nhua-phu-hpl',
    columns: [
      { key: 'stt', label: 'STT' },
      { key: 'loai_van', label: 'Loại ván' },
      { key: 'do_day', label: 'Độ dày' },
      { key: 'do_day_tp', label: 'Độ dày TP' },
      { key: 'gia_1m_le1', label: '1m LE1', type: 'number' },
      { key: 'gia_1m_le2', label: '1m LE2', type: 'number' },
      { key: 'gia_1m_lp1', label: '1m LP1', type: 'number' },
      { key: 'gia_1m_lp2', label: '1m LP2', type: 'number' },
      { key: 'gia_1m_lp3', label: '1m LP3', type: 'number' },
      { key: 'gia_2m_le1', label: '2m LE1', type: 'number' },
      { key: 'gia_2m_le2', label: '2m LE2', type: 'number' },
      { key: 'gia_2m_lp1', label: '2m LP1', type: 'number' },
      { key: 'gia_2m_lp2', label: '2m LP2', type: 'number' },
      { key: 'gia_2m_lp3', label: '2m LP3', type: 'number' },
    ],
    compute: { tinhToan: 'tinh-gia-one-laminate/tinh-toan' },
  },
  {
    slug: 'osb-ghep-ep-phu-hpl',
    label: 'OSB/Gỗ ghép/Ván ép phủ HPL',
    apiPath: 'osb-ghep-ep-phu-hpl',
    columns: [
      { key: 'stt', label: 'STT' },
      { key: 'loai_van', label: 'Loại ván' },
      { key: 'do_day', label: 'Độ dày' },
      { key: 'do_day_tp', label: 'Độ dày TP' },
      { key: 'gia_1m_le1', label: '1m LE1', type: 'number' },
      { key: 'gia_1m_le2', label: '1m LE2', type: 'number' },
      { key: 'gia_1m_lp1', label: '1m LP1', type: 'number' },
      { key: 'gia_1m_lp2', label: '1m LP2', type: 'number' },
      { key: 'gia_1m_lp3', label: '1m LP3', type: 'number' },
      { key: 'gia_2m_le1', label: '2m LE1', type: 'number' },
      { key: 'gia_2m_le2', label: '2m LE2', type: 'number' },
      { key: 'gia_2m_lp1', label: '2m LP1', type: 'number' },
      { key: 'gia_2m_lp2', label: '2m LP2', type: 'number' },
      { key: 'gia_2m_lp3', label: '2m LP3', type: 'number' },
    ],
    compute: { tinhToan: 'tinh-gia-one-laminate/tinh-toan' },
  },
  {
    slug: 'mirror',
    label: 'Mirror',
    apiPath: 'mirror',
    columns: [
      { key: 'stt', label: 'STT' },
      { key: 'nguon', label: 'Nguồn' },
      { key: 'loai', label: 'Loại' },
      { key: 'quy_cach', label: 'Quy cách' },
      { key: 'gia_1m', label: 'Giá 1 mặt', type: 'number' },
      { key: 'gia_2m', label: 'Giá 2 mặt', type: 'number' },
    ],
  },
  {
    slug: 'chi-nep',
    label: 'Chỉ Nẹp',
    apiPath: 'chi-nep',
    columns: [
      { key: 'stt', label: 'STT' },
      { key: 'nhom', label: 'Nhóm' },
      { key: 'ma_sp', label: 'Mã SP' },
      { key: 'kich_thuoc', label: 'Kích thước' },
      { key: 'gia', label: 'Giá', type: 'number' },
    ],
    compute: { autoAssign: 'chi-nep/auto-assign-ma-sp' },
  },
  {
    slug: 'keo-hat',
    label: 'Keo Hạt',
    apiPath: 'keo-hat',
    columns: [
      { key: 'stt', label: 'STT' },
      { key: 'ma', label: 'Mã' },
      { key: 'nhiet_do', label: 'Nhiệt độ' },
      { key: 'mau', label: 'Màu' },
      { key: 'gia_1kg', label: 'Giá 1 ký', type: 'number' },
      { key: 'gia_25kg', label: 'Giá bao 25 ký', type: 'number' },
    ],
  },
  {
    slug: '98-mau-melamine',
    label: '98 Màu Melamine Phổ Thông',
    apiPath: '98-mau-melamine',
    columns: [
      { key: 'stt', label: 'STT' },
      { key: 'wood_1', label: 'Wood' },
      { key: 'wood_2', label: '' },
      { key: 'wood_3', label: '' },
      { key: 'wood_4', label: '' },
      { key: 'wood_5', label: '' },
      { key: 'wood_6', label: '' },
      { key: 'wood_7', label: '' },
      { key: 'art', label: 'Art' },
      { key: 'color_code', label: '' },
      { key: 'color_name', label: 'Color' },
    ],
  },
  {
    slug: 'mau-melamine-2',
    label: 'Bảng màu Melamine (mới)',
    apiPath: 'mau-melamine-2',
    columns: [
      { key: 'ma_mau', label: 'Mã màu' },
      { key: 'nhom', label: 'Nhóm' },
      { key: 'phan_nhom', label: 'Phân nhóm' },
    ],
    compute: {
      tinhToan: 'tinh-gia-melamine-tonghop/tinh-toan',
      autoAssign: 'tinh-gia-melamine-tonghop/auto-assign-ma-sp',
      autoGenerate: 'tinh-gia-melamine-tonghop/auto-generate-ma-sp',
    },
  },
  {
    slug: 'melamine-plywood',
    label: 'Melamine Plywood',
    apiPath: 'melamine-plywood',
    columns: [
      { key: 'stt', label: 'STT' },
      { key: 'loai_cot', label: 'Loại cốt' },
      { key: 'do_day', label: 'Độ dày' },
      { key: 'gia_sang_trung', label: 'Giá Sáng/Trung', type: 'number' },
      { key: 'gia_toi', label: 'Giá Tối', type: 'number' },
      { key: 'gia_don_sac_101', label: 'Đơn sắc 101', type: 'number' },
      { key: 'gia_don_sac_khac_da', label: 'Đơn sắc khác đá', type: 'number' },
      { key: 'gia_don_sac_106', label: 'Đơn sắc 106', type: 'number' },
    ],
    compute: {
      tinhToan: 'tinh-gia-melamine-tonghop/tinh-toan',
      autoAssign: 'tinh-gia-melamine-tonghop/auto-assign-ma-sp',
      autoGenerate: 'tinh-gia-melamine-tonghop/auto-generate-ma-sp',
    },
  },
  {
    slug: 'melamine-nhua-osb-ghep',
    label: 'Ván nhựa/OSB/Gỗ ghép phủ Melamine',
    apiPath: 'melamine-nhua-osb-ghep',
    columns: [
      { key: 'stt', label: 'STT' },
      { key: 'loai_cot', label: 'Loại cốt' },
      { key: 'do_day', label: 'Độ dày' },
      { key: 'gia_sang_trung', label: 'Giá 2 mặt Sáng/Trung', type: 'number' },
      { key: 'gia_1m_sang_trung', label: 'Giá 1 mặt Sáng/Trung', type: 'number', readOnly: true },
      { key: 'gia_toi_don_sac', label: 'Giá 2 mặt Tối/Đơn sắc', type: 'number' },
      { key: 'gia_1m_toi_don_sac', label: 'Giá 1 mặt Tối/Đơn sắc', type: 'number', readOnly: true },
      { key: 'gia_chum_104_106', label: 'Giá 2 mặt chùm 104/106', type: 'number' },
      { key: 'gia_1m_chum_104_106', label: 'Giá 1 mặt chùm 104/106', type: 'number', readOnly: true },
    ],
    compute: {
      tinhToan: 'tinh-gia-melamine-tonghop/tinh-toan',
      autoAssign: 'tinh-gia-melamine-tonghop/auto-assign-ma-sp',
      autoGenerate: 'tinh-gia-melamine-tonghop/auto-generate-ma-sp',
    },
  },
]
